// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.30/05       [335365]
Creator        : gerbaudo
Date           : Mon Jan 13 04:56:38 2014
Host           : Linux lxbuild147.cern.ch 2.6.18-194.26.1.el5 #1 SMP Wed Nov 10 09:51:11 CET 2010 i686 i686 i386 GNU/Linux
Dir            : /data7/atlas/gerbaudo/wh/Susy2013_Nt_01_04_dev/SusyTest0/run
Training events: 41827
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "50" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "41827" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mll                           mll                           mll                           mll                                                             'F'    [19.6338844299,1527.23803711]
mtllmet                       mtllmet                       mtllmet                       mtllmet                                                         'F'    [0.00592454569414,1030.39794922]
ht                            ht                            ht                            ht                                                              'F'    [100.771408081,2392.35083008]
metrel                        metrel                        metrel                        metrel                                                          'F'    [0.000144434539834,407.61315918]
mt2j                          mt2j                          mt2j                          mt2j                                                            'F'    [22.6929779053,1188.41894531]
mljj                          mljj                          mljj                          mljj                                                            'F'    [25.8547725677,2671.67578125]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mll", "mtllmet", "ht", "metrel", "mt2j", "mljj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 19.6338844299316;
      fVmax[0] = 1527.23803710938;
      fVmin[1] = 0.00592454569414258;
      fVmax[1] = 1030.39794921875;
      fVmin[2] = 100.771408081055;
      fVmax[2] = 2392.35083007812;
      fVmin[3] = 0.000144434539834037;
      fVmax[3] = 407.613159179688;
      fVmin[4] = 22.6929779052734;
      fVmax[4] = 1188.4189453125;
      fVmin[5] = 25.854772567749;
      fVmax[5] = 2671.67578125;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.66049826505106);
  fForest.push_back( 
NN(
0, 
0, 
-1, 91.4246, 1, -1, 0.0348579,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.830249);
  fForest.push_back( 
NN(
0, 
0, 
-1, 91.4246, 1, -1, 0.159695,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.421577);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332177,-99) , 
2, 190.743, 0, 0, 0.479709,-99) , 
NN(
0, 
0, 
-1, 125.3, 1, -1, 0.327652,-99) , 
0, 50.3986, 1, 0, 0.377275,-99) , 
NN(
0, 
0, 
-1, 154.599, 1, -1, 0.22708,-99) , 
0, 91.4246, 1, 0, 0.303592,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.327494);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408374,-99) , 
5, 123.573, 1, 0, 0.53965,-99) , 
NN(
0, 
0, 
-1, 102.659, 1, -1, 0.411999,-99) , 
2, 266.184, 0, 0, 0.453476,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356024,-99) , 
1, 213.102, 0, 0, 0.36365,-99) , 
NN(
0, 
0, 
-1, 511.822, 1, -1, 0.207851,-99) , 
0, 91.4246, 1, 0, 0.284636,-99) , 
5, 151.846, 1, 0, 0.367847,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.206279);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351016,-99) , 
2, 153.615, 0, 0, 0.538444,-99) , 
NN(
0, 
0, 
-1, 111.525, 1, -1, 0.450184,-99) , 
5, 115.848, 1, 0, 0.5024,-99) , 
NN(
0, 
0, 
-1, 91.4246, 1, -1, 0.353233,-99) , 
5, 151.846, 1, 0, 0.428327,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.163252);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379071,-99) , 
2, 157.437, 0, 0, 0.522713,-99) , 
NN(
0, 
0, 
-1, 64.2067, 1, -1, 0.398617,-99) , 
5, 324.19, 1, 0, 0.51269,-99) , 
NN(
0, 
0, 
-1, 154.599, 1, -1, 0.377022,-99) , 
0, 91.4246, 1, 0, 0.450529,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.135579);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 360.707, 0, 1, 0.529341,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350981,-99) , 
4, 86.7912, 1, 0, 0.443123,-99) , 
2, 211.046, 0, 0, 0.497402,-99) , 
NN(
0, 
0, 
-1, 91.4246, 1, -1, 0.406779,-99) , 
5, 151.846, 1, 0, 0.453036,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.112925);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458769,-99) , 
2, 206.296, 0, 0, 0.501858,-99) , 
NN(
0, 
0, 
-1, 38.4889, 0, -1, 0.437757,-99) , 
0, 81.1664, 1, 0, 0.473466,-99) , 
NN(
0, 
0, 
-1, 537.028, 1, -1, 0.366567,-99) , 
0, 163.215, 1, 0, 0.457177,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0870227);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465591,-99) , 
2, 261.862, 0, 0, 0.485394,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.246084,-99) , 
2, 419.414, 0, 0, 0.369339,-99) , 
0, 221.353, 1, 0, 0.4792,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365702,-99) , 
0, 64.3602, 1, 0, 0.46764,-99) , 
NN(
0, 
0, 
-1, 505.824, 1, -1, 0.315037,-99) , 
0, 91.7079, 1, 0, 0.390617,-99) , 
5, 277.838, 1, 0, 0.4665,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0948999);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469994,-99) , 
4, 108.179, 1, 0, 0.495737,-99) , 
NN(
0, 
0, 
-1, 58.232, 1, -1, 0.415038,-99) , 
5, 249.257, 1, 0, 0.482475,-99) , 
NN(
0, 
0, 
-1, 537.028, 1, -1, 0.39289,-99) , 
0, 163.215, 1, 0, 0.469037,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0469419);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 241.825, 1, -1, 0.480839,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 209.195, 0, 0, 0.464687,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.135438,-99) , 
0, 92.3257, 1, 0, 0.294345,-99) , 
5, 529.821, 1, 0, 0.47666,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0420909);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35484,-99) , 
0, 271.782, 1, 0, 0.502418,-99) , 
NN(
0, 
0, 
-1, 39.3033, 0, -1, 0.446486,-99) , 
5, 241.825, 1, 0, 0.492566,-99) , 
NN(
0, 
0, 
-1, 92.3257, 1, -1, 0.29363,-99) , 
5, 529.821, 1, 0, 0.488147,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0586004);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505385,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423202,-99) , 
2, 164.491, 0, 0, 0.498657,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4334,-99) , 
5, 105.462, 1, 0, 0.45453,-99) , 
0, 120.493, 1, 0, 0.486133,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 209.195, 0, 0, 0.465216,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.146206,-99) , 
0, 92.3257, 1, 0, 0.302436,-99) , 
5, 529.821, 1, 0, 0.482085,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0481665);
  fForest.push_back( 
NN(
0, 
0, 
-1, 529.821, 1, -1, 0.475935,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0374827);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472449,-99) , 
3, 17.0366, 0, 0, 0.493109,-99) , 
NN(
0, 
0, 
-1, 83.0629, 0, -1, 0.246641,-99) , 
5, 49.8515, 0, 0, 0.491857,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 209.195, 0, 0, 0.46469,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.160043,-99) , 
0, 92.3257, 1, 0, 0.311749,-99) , 
5, 529.821, 1, 0, 0.487961,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0285713);
  fForest.push_back( 
NN(
0, 
0, 
-1, 529.821, 1, -1, 0.485718,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0142908);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 49.8515, 0, -1, 0.496694,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 89.6244, 1, 0, 0.463744,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.169123,-99) , 
0, 92.3257, 1, 0, 0.31729,-99) , 
5, 529.821, 1, 0, 0.492858,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0185247);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338081,-99) , 
0, 372.642, 1, 0, 0.501462,-99) , 
NN(
0, 
0, 
-1, 83.0629, 0, -1, 0.261872,-99) , 
5, 49.8515, 0, 0, 0.500267,-99) , 
NN(
0, 
0, 
-1, 92.3257, 1, -1, 0.317053,-99) , 
5, 529.821, 1, 0, 0.496359,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0392377);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48645,-99) , 
4, 103.381, 1, 0, 0.496912,-99) , 
NN(
0, 
0, 
-1, 83.0629, 0, -1, 0.265468,-99) , 
5, 49.8515, 0, 0, 0.495763,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 209.195, 0, 0, 0.465277,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.173785,-99) , 
0, 92.3257, 1, 0, 0.321078,-99) , 
5, 529.821, 1, 0, 0.492048,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0532882);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471291,-99) , 
5, 243.856, 1, 0, 0.508543,-99) , 
NN(
0, 
0, 
-1, 104.105, 1, -1, 0.468281,-99) , 
2, 209.894, 0, 0, 0.499103,-99) , 
NN(
0, 
0, 
-1, 92.3257, 1, -1, 0.320416,-99) , 
5, 529.821, 1, 0, 0.495327,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0144116);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 49.8515, 0, -1, 0.496358,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 89.6244, 1, 0, 0.470064,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.187473,-99) , 
0, 92.3257, 1, 0, 0.332129,-99) , 
5, 529.821, 1, 0, 0.492916,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0130153);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.501078,-99) , 
NN(
0, 
0, 
-1, 83.0629, 0, -1, 0.271369,-99) , 
5, 49.8515, 0, 0, 0.499961,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 89.6244, 1, 0, 0.466954,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.189678,-99) , 
0, 92.3257, 1, 0, 0.331885,-99) , 
5, 529.821, 1, 0, 0.496447,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0134002);
  fForest.push_back( 
NN(
0, 
0, 
-1, 529.821, 1, -1, 0.4933,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0129891);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.50118,-99) , 
NN(
0, 
0, 
-1, 83.0629, 0, -1, 0.276624,-99) , 
5, 49.8515, 0, 0, 0.500094,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 89.6244, 1, 0, 0.467478,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.193772,-99) , 
0, 92.3257, 1, 0, 0.334641,-99) , 
5, 529.821, 1, 0, 0.49665,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0129836);
  fForest.push_back( 
NN(
0, 
0, 
-1, 529.821, 1, -1, 0.493509,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0127803);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.501184,-99) , 
NN(
0, 
0, 
-1, 83.0629, 0, -1, 0.281851,-99) , 
5, 49.8515, 0, 0, 0.500129,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 209.195, 0, 0, 0.467899,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.197862,-99) , 
0, 92.3257, 1, 0, 0.337314,-99) , 
5, 529.821, 1, 0, 0.496754,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0126757);
  fForest.push_back( 
NN(
0, 
0, 
-1, 529.821, 1, -1, 0.493662,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0125379);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.501163,-99) , 
NN(
0, 
0, 
-1, 83.0629, 0, -1, 0.287032,-99) , 
5, 49.8515, 0, 0, 0.500139,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 89.6244, 1, 0, 0.468284,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.201933,-99) , 
0, 92.3257, 1, 0, 0.339932,-99) , 
5, 529.821, 1, 0, 0.496831,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0124058);
  fForest.push_back( 
NN(
0, 
0, 
-1, 529.821, 1, -1, 0.493797,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0122775);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.501135,-99) , 
NN(
0, 
0, 
-1, 83.0629, 0, -1, 0.292164,-99) , 
5, 49.8515, 0, 0, 0.500141,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 209.195, 0, 0, 0.468655,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.205983,-99) , 
0, 92.3257, 1, 0, 0.342504,-99) , 
5, 529.821, 1, 0, 0.496899,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0121605);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 49.8515, 0, -1, 0.497105,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 89.6244, 1, 0, 0.46599,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.207998,-99) , 
0, 92.3257, 1, 0, 0.34229,-99) , 
5, 529.821, 1, 0, 0.493927,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0120249);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.50111,-99) , 
NN(
0, 
0, 
-1, 83.0629, 0, -1, 0.297243,-99) , 
5, 49.8515, 0, 0, 0.500145,-99) , 
NN(
0, 
0, 
-1, 92.3257, 1, -1, 0.342079,-99) , 
5, 529.821, 1, 0, 0.496907,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0250496);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493745,-99) , 
4, 233.948, 0, 0, 0.497553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.497172,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 209.195, 0, 0, 0.466344,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.21201,-99) , 
0, 92.3257, 1, 0, 0.344791,-99) , 
5, 529.821, 1, 0, 0.494056,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0213003);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.210799,-99) , 
4, 387.737, 1, 0, 0.50383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 532.289, 0, 0, 0.354384,-99) , 
0, 372.642, 1, 0, 0.50253,-99) , 
NN(
0, 
0, 
-1, 92.3257, 1, -1, 0.344353,-99) , 
5, 529.821, 1, 0, 0.499306,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0114827);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 466.478, 1, -1, 0.497273,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 89.6244, 1, 0, 0.466197,-99) , 
NN(
0, 
0, 
-1, 636.022, 1, -1, 0.219857,-99) , 
0, 92.3257, 1, 0, 0.349178,-99) , 
5, 529.821, 1, 0, 0.494264,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0115051);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302968,-99) , 
5, 49.8515, 0, 0, 0.500517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.500143,-99) , 
NN(
0, 
0, 
-1, 235.817, 1, -1, 0.348977,-99) , 
5, 529.821, 1, 0, 0.497077,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0218645);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49473,-99) , 
4, 64.9439, 1, 0, 0.497668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.497298,-99) , 
NN(
0, 
0, 
-1, 235.817, 1, -1, 0.351596,-99) , 
5, 529.821, 1, 0, 0.494348,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0151676);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309435,-99) , 
5, 49.8515, 0, 0, 0.502633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.502264,-99) , 
NN(
0, 
0, 
-1, 235.817, 1, -1, 0.356596,-99) , 
5, 529.821, 1, 0, 0.499323,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0138471);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.216619,-99) , 
4, 387.737, 1, 0, 0.499773,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.806694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.180606,-99) , 
2, 835.162, 0, 0, 0.354105,-99) , 
0, 372.642, 1, 0, 0.498513,-99) , 
NN(
0, 
0, 
-1, 235.817, 1, -1, 0.360084,-99) , 
5, 529.821, 1, 0, 0.495724,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0150731);
  fForest.push_back( 
NN(
0, 
0, 
-1, 529.821, 1, -1, 0.492464,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.00799498);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.312948,-99) , 
5, 49.8515, 0, 0, 0.499242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.498883,-99) , 
NN(
0, 
0, 
-1, 235.817, 1, -1, 0.366774,-99) , 
5, 529.821, 1, 0, 0.496232,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0320812);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450313,-99) , 
2, 178.71, 0, 0, 0.498736,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.769152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361186,-99) , 
0, 343.885, 0, 0, 0.395445,-99) , 
2, 646.386, 1, 0, 0.495996,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.833252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.694876,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.101432,-99) , 
2, 837.716, 0, 0, 0.295763,-99) , 
0, 378.587, 1, 0, 0.494334,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0401895);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485574,-99) , 
0, 36.7073, 1, 0, 0.490518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.490007,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.828747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.69174,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.104394,-99) , 
2, 837.716, 0, 0, 0.296886,-99) , 
0, 378.587, 1, 0, 0.488424,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.00986472);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498112,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.822968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.687708,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.108211,-99) , 
2, 837.716, 0, 0, 0.298332,-99) , 
0, 378.587, 1, 0, 0.496498,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0106601);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.501087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500579,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.821526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.686701,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.109167,-99) , 
2, 837.716, 0, 0, 0.298694,-99) , 
0, 378.587, 1, 0, 0.498954,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0195963);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45587,-99) , 
0, 190.368, 1, 0, 0.498426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.497923,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.819957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.685605,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.110208,-99) , 
2, 837.716, 0, 0, 0.299088,-99) , 
0, 378.587, 1, 0, 0.496329,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0180454);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.49391,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.817046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.683569,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.112144,-99) , 
2, 837.716, 0, 0, 0.299821,-99) , 
0, 378.587, 1, 0, 0.492365,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.00902269);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498421,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.814333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.681669,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.113954,-99) , 
2, 837.716, 0, 0, 0.300505,-99) , 
0, 378.587, 1, 0, 0.496856,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0105536);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.501171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500677,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.812965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.68071,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.114868,-99) , 
2, 837.716, 0, 0, 0.30085,-99) , 
0, 378.587, 1, 0, 0.499102,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.00968802);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498047,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.811355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.679581,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.115945,-99) , 
2, 837.716, 0, 0, 0.301258,-99) , 
0, 378.587, 1, 0, 0.496502,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0100293);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500469,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.678537,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.116942,-99) , 
2, 837.716, 0, 0, 0.301634,-99) , 
0, 378.587, 1, 0, 0.498914,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.00976426);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.49797,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.808319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.677449,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.117982,-99) , 
2, 837.716, 0, 0, 0.302027,-99) , 
0, 378.587, 1, 0, 0.496443,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.00980524);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500411,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.806801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.676383,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.119002,-99) , 
2, 837.716, 0, 0, 0.302412,-99) , 
0, 378.587, 1, 0, 0.498874,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.00969316);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.497968,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.805268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.675305,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.120033,-99) , 
2, 837.716, 0, 0, 0.302801,-99) , 
0, 378.587, 1, 0, 0.496458,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.009659);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500391,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.674233,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.121061,-99) , 
2, 837.716, 0, 0, 0.303189,-99) , 
0, 378.587, 1, 0, 0.498871,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.00950921);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.497984,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.766942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.258236,-99) , 
4, 236.476, 1, 0, 0.525393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.303578,-99) , 
0, 378.587, 1, 0, 0.496491,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.00941893);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500362,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.765238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260062,-99) , 
4, 236.476, 1, 0, 0.525335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.303844,-99) , 
0, 378.587, 1, 0, 0.498857,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.00949299);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498015,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.802774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.674015,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.12189,-99) , 
2, 837.716, 0, 0, 0.304109,-99) , 
0, 378.587, 1, 0, 0.496534,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.00938809);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500388,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.763968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261451,-99) , 
4, 236.476, 1, 0, 0.525442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.304492,-99) , 
0, 378.587, 1, 0, 0.498898,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0092583);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498048,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.762271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.263268,-99) , 
4, 236.476, 1, 0, 0.525383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.304758,-99) , 
0, 378.587, 1, 0, 0.496583,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.00937305);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500363,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.801824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.673805,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.122705,-99) , 
2, 837.716, 0, 0, 0.305021,-99) , 
0, 378.587, 1, 0, 0.498887,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0274384);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492801,-99) , 
4, 86.0693, 1, 0, 0.499286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 466.478, 1, 0, 0.498947,-99) , 
NN(
0, 
0, 
-1, 235.817, 1, -1, 0.378866,-99) , 
5, 529.821, 1, 0, 0.496576,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.012978);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417388,-99) , 
5, 503.431, 1, 0, 0.502042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.501687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.501135,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0114778);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44831,-99) , 
0, 225.714, 1, 0, 0.498937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.498586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.498042,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.00898085);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.49551,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.00765504);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429094,-99) , 
2, 152.729, 0, 0, 0.498641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.498294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.497755,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.00807284);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.495964,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.00760561);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432951,-99) , 
2, 152.729, 0, 0, 0.498862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.498517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.497982,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.00759602);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.496202,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.00651798);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420484,-99) , 
5, 503.431, 1, 0, 0.498974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.498632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.498101,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.00754174);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451973,-99) , 
0, 225.714, 1, 0, 0.497415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.497075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.496547,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0102342);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.494883,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.00511709);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.497441,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.00737097);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424271,-99) , 
5, 503.431, 1, 0, 0.499582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.498721,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.00607386);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.496963,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.00804534);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436694,-99) , 
2, 152.729, 0, 0, 0.499337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.498482,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0223547);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485338,-99) , 
2, 256.644, 0, 0, 0.497448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.497115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.496599,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0105858);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.497326,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.765134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.272004,-99) , 
4, 236.476, 1, 0, 0.533857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.31107,-99) , 
0, 378.587, 1, 0, 0.495934,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.00807562);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499973,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.763227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.274105,-99) , 
4, 236.476, 1, 0, 0.533782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.311374,-99) , 
0, 378.587, 1, 0, 0.498568,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.00925936);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.49796,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.761764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.275715,-99) , 
4, 236.476, 1, 0, 0.533724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.311607,-99) , 
0, 378.587, 1, 0, 0.496576,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.00875825);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500274,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.805782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.683915,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.125932,-99) , 
2, 837.716, 0, 0, 0.311876,-99) , 
0, 378.587, 1, 0, 0.49888,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.00894968);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498091,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.76048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27715,-99) , 
4, 236.476, 1, 0, 0.533805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.312234,-99) , 
0, 378.587, 1, 0, 0.496719,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.00862106);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500329,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.758846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278946,-99) , 
4, 236.476, 1, 0, 0.53374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.312494,-99) , 
0, 378.587, 1, 0, 0.498947,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.00871018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498179,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.757265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280683,-99) , 
4, 236.476, 1, 0, 0.533676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.312747,-99) , 
0, 378.587, 1, 0, 0.496819,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.00879775);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500357,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.805199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.684125,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.126589,-99) , 
2, 837.716, 0, 0, 0.313004,-99) , 
0, 378.587, 1, 0, 0.498987,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00869556);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498164,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.756069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282018,-99) , 
4, 236.476, 1, 0, 0.533759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.313362,-99) , 
0, 378.587, 1, 0, 0.496816,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.00848151);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500338,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.754462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283782,-99) , 
4, 236.476, 1, 0, 0.533694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.313619,-99) , 
0, 378.587, 1, 0, 0.49898,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.00874037);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498223,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.80434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.683919,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.127358,-99) , 
2, 837.716, 0, 0, 0.313872,-99) , 
0, 378.587, 1, 0, 0.496887,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00855364);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500408,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.753298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.285079,-99) , 
4, 236.476, 1, 0, 0.533775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.314228,-99) , 
0, 378.587, 1, 0, 0.499063,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00836666);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498276,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.751705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286825,-99) , 
4, 236.476, 1, 0, 0.53371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.314483,-99) , 
0, 378.587, 1, 0, 0.496952,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.00838878);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500368,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.750141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.28854,-99) , 
4, 236.476, 1, 0, 0.533645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.314734,-99) , 
0, 378.587, 1, 0, 0.499034,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.00607394);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.496963,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.00671291);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423095,-99) , 
5, 503.431, 1, 0, 0.499273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.498962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.498482,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00873078);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498192,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 994.184, 1, 0, 0.684682,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.128013,-99) , 
2, 837.716, 0, 0, 0.315066,-99) , 
0, 378.587, 1, 0, 0.49688,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.00831469);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500374,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.74894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290244,-99) , 
4, 236.476, 1, 0, 0.534067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.315421,-99) , 
0, 378.587, 1, 0, 0.499054,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.00821045);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498301,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.747374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29196,-99) , 
4, 236.476, 1, 0, 0.534001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.315673,-99) , 
0, 378.587, 1, 0, 0.497001,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.00846942);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500354,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 169.53, 0, 0, 0.684459,-99) , 
NN(
0, 
0, 
-1, 29.8206, 1, -1, 0.128782,-99) , 
2, 837.716, 0, 0, 0.315922,-99) , 
0, 378.587, 1, 0, 0.499045,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0145841);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472268,-99) , 
0, 157.021, 1, 0, 0.497728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.497425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.496954,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.011053);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.494474,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00552651);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.497237,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.00654586);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426778,-99) , 
5, 503.431, 1, 0, 0.499383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.498618,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.00588672);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.497057,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.00294336);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498528,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.00245693);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499726,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499264,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.00269533);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498652,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.00257085);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499326,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.00262807);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498686,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.00259433);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499343,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.00260614);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498697,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.00259517);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499348,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.00259561);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498702,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.00259035);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499351,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.00258796);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498706,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.00258414);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499353,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.00258105);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498709,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.00257761);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499355,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.00257436);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498713,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.00257102);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.49981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499356,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.00256774);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498716,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.00256445);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.49981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499358,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.00256117);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498719,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0025579);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.49936,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.00255464);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498723,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.00255139);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499361,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.00254814);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498726,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.00254491);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499363,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.00254168);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498729,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.00253846);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499365,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.00253524);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498732,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.00253204);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499366,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.00252884);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498736,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.00252566);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499368,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.00252248);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498739,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0025193);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499369,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.00251614);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498742,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.00251298);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.5001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499371,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.00250984);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498745,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.00250669);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.5001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499373,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.00250356);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498748,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.00250044);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.5001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499374,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.00249732);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498751,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.00249421);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.5001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499376,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.00249111);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498754,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.00248802);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499377,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.00248493);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498758,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.00248185);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499379,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.00247878);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498761,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.00247572);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.49938,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.00247266);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498764,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.00246961);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499382,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.00246657);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498767,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.00246354);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499383,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.00246051);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.49877,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.00245749);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499385,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.00245448);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498773,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.00245148);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499386,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.00719565);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500009,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.752665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3029,-99) , 
4, 236.476, 1, 0, 0.544693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.32417,-99) , 
0, 378.587, 1, 0, 0.498776,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.0060034);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.496998,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.0030017);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498499,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.00214904);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.499954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.49925,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.00257146);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498714,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.00235557);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.50006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499357,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.00626579);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430523,-99) , 
5, 503.431, 1, 0, 0.499472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.49877,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.0054501);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.497275,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.00272505);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498637,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.00224964);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499319,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.0024833);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498758,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.002362);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499379,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.0024184);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498791,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.00238586);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.50009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499395,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.00239785);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498801,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.00238756);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499401,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.00238844);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498806,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.00238373);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499403,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.00710858);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.50037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500022,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.752791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307004,-99) , 
4, 236.476, 1, 0, 0.547334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.326312,-99) , 
0, 378.587, 1, 0, 0.498809,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.00589421);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.497053,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.00294711);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498526,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.00207689);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.499948,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499263,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.00250832);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498746,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.00228816);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499373,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.0023942);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498803,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.00233696);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499401,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.00236146);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498819,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.00234505);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.50009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.49941,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.00234913);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498825,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.00234296);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499413,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.00234193);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498829,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.00233834);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499415,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.00233604);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498832,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.00233311);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499416,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.0023305);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498835,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.00232774);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499417,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.00232507);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1192, 1, -1, 0.498837,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.00232236);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 590.959, 1, 0, 0.500091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.499827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.499419,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.00702927);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.500373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.500034,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.752925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310795,-99) , 
4, 236.476, 1, 0, 0.549701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.328348,-99) , 
0, 378.587, 1, 0, 0.49884,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.0157341);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494887,-99) , 
4, 241.257, 0, 0, 0.497769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.497508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.497103,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.0101569);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1142.87, 1, 0, 0.50196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.501624,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.754541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30939,-99) , 
4, 236.476, 1, 0, 0.550153,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 586.887, 0, 0, 0.329783,-99) , 
0, 378.587, 1, 0, 0.500432,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.0204);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494577,-99) , 
4, 79.8968, 1, 0, 0.499154,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 837.848, 0, 0, 0.335825,-99) , 
4, 423.276, 1, 0, 0.498322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.497922,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.0111678);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499425,-99) , 
4, 232.44, 0, 0, 0.503012,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 837.848, 0, 0, 0.333966,-99) , 
4, 423.276, 1, 0, 0.502156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.501756,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.0202726);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44523,-99) , 
2, 152.729, 0, 0, 0.505337,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 837.848, 0, 0, 0.332941,-99) , 
4, 423.276, 1, 0, 0.504465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 1192, 1, 0, 0.504067,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
