// Class: ReadBDT_mm_ge2j
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_mm_ge2j
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.30/05       [335365]
Creator        : gerbaudo
Date           : Tue Jan 14 18:38:01 2014
Host           : Linux lxbuild147.cern.ch 2.6.18-194.26.1.el5 #1 SMP Wed Nov 10 09:51:11 CET 2010 i686 i686 i386 GNU/Linux
Dir            : /data7/atlas/gerbaudo/wh/Susy2013_Nt_01_04_dev/SusyTest0/run
Training events: 14769
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "50" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "4" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "14769" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
mll                           mll                           mll                           mll                                                             'F'    [20.001121521,1173.01306152]
mtmin                         mtmin                         mtmin                         mtmin                                                           'F'    [0.00421222485602,218.384780884]
mtmax                         mtmax                         mtmax                         mtmax                                                           'F'    [2.87438988686,782.94140625]
mtllmet                       mtllmet                       mtllmet                       mtllmet                                                         'F'    [0.00744388159364,761.738464355]
ht                            ht                            ht                            ht                                                              'F'    [63.8003120422,2468.89257812]
metrel                        metrel                        metrel                        metrel                                                          'F'    [0.000768656318542,341.422973633]
dphill                        dphill                        dphill                        dphill                                                          'F'    [0.000325202941895,3.141518116]
detall                        detall                        detall                        detall                                                          'F'    [0.000315725803375,4.76091098785]
mt2j                          mt2j                          mt2j                          mt2j                                                            'F'    [0,943.108398438]
mljj                          mljj                          mljj                          mljj                                                            'F'    [0,2297.39331055]
dphijj                        dphijj                        dphijj                        dphijj                                                          'F'    [0,3.1410548687]
detajj                        detajj                        detajj                        detajj                                                          'F'    [0,4.82226705551]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_mm_ge2jNode
   
#ifndef BDT_mm_ge2jNode__def
#define BDT_mm_ge2jNode__def
   
class BDT_mm_ge2jNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_mm_ge2jNode ( BDT_mm_ge2jNode* left,BDT_mm_ge2jNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_mm_ge2jNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_mm_ge2jNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_mm_ge2jNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_mm_ge2jNode*   fLeft;     // pointer to the left daughter node
   BDT_mm_ge2jNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_mm_ge2jNode::~BDT_mm_ge2jNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_mm_ge2jNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_mm_ge2jNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_mm_ge2j : public IClassifierReader {

 public:

   // constructor
   ReadBDT_mm_ge2j( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_mm_ge2j" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mll", "mtmin", "mtmax", "mtllmet", "ht", "metrel", "dphill", "detall", "mt2j", "mljj", "dphijj", "detajj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 20.0011215209961;
      fVmax[0] = 1173.01306152344;
      fVmin[1] = 0.00421222485601902;
      fVmax[1] = 218.384780883789;
      fVmin[2] = 2.87438988685608;
      fVmax[2] = 782.94140625;
      fVmin[3] = 0.00744388159364462;
      fVmax[3] = 761.738464355469;
      fVmin[4] = 63.8003120422363;
      fVmax[4] = 2468.892578125;
      fVmin[5] = 0.000768656318541616;
      fVmax[5] = 341.422973632812;
      fVmin[6] = 0.000325202941894531;
      fVmax[6] = 3.14151811599731;
      fVmin[7] = 0.000315725803375244;
      fVmax[7] = 4.760910987854;
      fVmin[8] = 0;
      fVmax[8] = 943.1083984375;
      fVmin[9] = 0;
      fVmax[9] = 2297.39331054688;
      fVmin[10] = 0;
      fVmax[10] = 3.14105486869812;
      fVmin[11] = 0;
      fVmax[11] = 4.82226705551147;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_mm_ge2j() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_mm_ge2jNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_mm_ge2j::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_mm_ge2jNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_mm_ge2jNode*)current->GetRight();
         else current=(BDT_mm_ge2jNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_mm_ge2j::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.4958436381885);
  fForest.push_back( 
NN(
0, 
0, 
-1, 178.329, 0, -1, 0.0478028,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.747922);
  fForest.push_back( 
NN(
0, 
0, 
-1, 178.329, 0, -1, 0.183046,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.467063);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377341,-99) , 
2, 94.4497, 0, 0, 0.495814,-99) , 
NN(
0, 
0, 
-1, 1.29563, 1, -1, 0.173304,-99) , 
9, 218.799, 1, 0, 0.429137,-99) , 
NN(
0, 
0, 
-1, 145.597, 0, -1, 0.18464,-99) , 
4, 178.329, 0, 0, 0.321274,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.286732);
  fForest.push_back( 
NN(
0, 
0, 
-1, 178.329, 0, -1, 0.360438,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.257577);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.140316,-99) , 
7, 2.72103, 1, 0, 0.525495,-99) , 
NN(
0, 
0, 
-1, 1.07935, 1, -1, 0.179676,-99) , 
4, 505.557, 1, 0, 0.500258,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293419,-99) , 
9, 117.114, 1, 0, 0.497167,-99) , 
NN(
0, 
0, 
-1, 1.798, 1, -1, 0.196429,-99) , 
4, 145.597, 0, 0, 0.324882,-99) , 
4, 178.329, 0, 0, 0.428804,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.198261);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.94735, 1, -1, 0.425813,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.189911,-99) , 
6, 2.23837, 0, 0, 0.308227,-99) , 
NN(
0, 
0, 
-1, 35.6756, 0, -1, 0.114526,-99) , 
4, 134.041, 0, 0, 0.212143,-99) , 
2, 40.0204, 0, 0, 0.403118,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.180725);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431352,-99) , 
10, 0.598296, 0, 0, 0.485237,-99) , 
NN(
0, 
0, 
-1, 1.34533, 1, -1, 0.133164,-99) , 
7, 2.94735, 1, 0, 0.474848,-99) , 
NN(
0, 
0, 
-1, 11.0303, 0, -1, 0.22804,-99) , 
2, 40.0204, 0, 0, 0.449685,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.146736);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338573,-99) , 
4, 144.396, 0, 0, 0.490177,-99) , 
NN(
0, 
0, 
-1, 65.0422, 0, -1, 0.100807,-99) , 
9, 437.599, 1, 0, 0.479564,-99) , 
NN(
0, 
0, 
-1, 11.0303, 0, -1, 0.261404,-99) , 
2, 40.0204, 0, 0, 0.458066,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.219715);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305393,-99) , 
4, 457.259, 1, 0, 0.529074,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302112,-99) , 
0, 66.2854, 0, 0, 0.407592,-99) , 
1, 38.9426, 0, 0, 0.466449,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317192,-99) , 
9, 83.3137, 0, 0, 0.388663,-99) , 
NN(
0, 
0, 
-1, 100.276, 1, -1, 0.204887,-99) , 
9, 109.4, 1, 0, 0.316035,-99) , 
7, 1.81388, 1, 0, 0.440752,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.18813);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496949,-99) , 
9, 52.0795, 0, 0, 0.53496,-99) , 
NN(
0, 
0, 
-1, 0.87756, 1, -1, 0.376408,-99) , 
9, 109.4, 1, 0, 0.484378,-99) , 
NN(
0, 
0, 
-1, 611.263, 1, -1, 0.388745,-99) , 
5, 32.5172, 0, 0, 0.427698,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0827724);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310443,-99) , 
4, 130.664, 0, 0, 0.480134,-99) , 
NN(
0, 
0, 
-1, 27.4199, 1, -1, 0.101269,-99) , 
9, 546.998, 1, 0, 0.475426,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 225.799, 1, 0, 0.343405,-99) , 
NN(
0, 
0, 
-1, 128.072, 0, -1, 0.0525457,-99) , 
6, 1.34533, 1, 0, 0.173728,-99) , 
7, 2.94735, 1, 0, 0.467603,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0940126);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.453132,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0823897);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335313,-99) , 
4, 117.46, 0, 0, 0.495534,-99) , 
NN(
0, 
0, 
-1, 1.01576, 1, -1, 0.364271,-99) , 
9, 218.799, 1, 0, 0.4816,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0430229,-99) , 
0, 294.528, 1, 0, 0.476514,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0732925);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 156.154, 1, -1, 0.474851,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.127413,-99) , 
9, 546.998, 1, 0, 0.470918,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 225.799, 1, 0, 0.344436,-99) , 
NN(
0, 
0, 
-1, 142.734, 0, -1, 0.0595926,-99) , 
6, 1.34533, 1, 0, 0.181052,-99) , 
7, 2.94735, 1, 0, 0.463792,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0879276);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394723,-99) , 
9, 156.154, 1, 0, 0.493154,-99) , 
NN(
0, 
0, 
-1, 27.4199, 1, -1, 0.126225,-99) , 
9, 546.998, 1, 0, 0.489105,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 225.799, 1, 0, 0.336434,-99) , 
NN(
0, 
0, 
-1, 142.734, 0, -1, 0.063835,-99) , 
6, 1.34533, 1, 0, 0.181341,-99) , 
7, 2.94735, 1, 0, 0.481703,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0623703);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 130.664, 0, -1, 0.479491,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.136246,-99) , 
9, 546.998, 1, 0, 0.475816,-99) , 
NN(
0, 
0, 
-1, 1.34533, 1, -1, 0.181706,-99) , 
7, 2.94735, 1, 0, 0.468916,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.076213);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366866,-99) , 
4, 130.664, 0, 0, 0.495072,-99) , 
NN(
0, 
0, 
-1, 27.4199, 1, -1, 0.135112,-99) , 
9, 546.998, 1, 0, 0.491301,-99) , 
NN(
0, 
0, 
-1, 1.34533, 1, -1, 0.191164,-99) , 
7, 2.94735, 1, 0, 0.484386,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.092166);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453441,-99) , 
5, 29.2769, 0, 0, 0.482595,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.213774,-99) , 
0, 99.2664, 1, 0, 0.288443,-99) , 
7, 2.64232, 1, 0, 0.475511,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0499558,-99) , 
0, 294.528, 1, 0, 0.471096,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.120987);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455904,-99) , 
0, 58.6776, 0, 0, 0.512707,-99) , 
NN(
0, 
0, 
-1, 328.199, 1, -1, 0.441603,-99) , 
7, 0.880984, 1, 0, 0.47823,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0545159,-99) , 
0, 294.528, 1, 0, 0.473999,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0671285);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4387,-99) , 
9, 130.129, 1, 0, 0.495385,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.137611,-99) , 
9, 546.998, 1, 0, 0.491959,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0610989,-99) , 
0, 294.528, 1, 0, 0.487858,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0861199);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461661,-99) , 
10, 1.19659, 0, 0, 0.487067,-99) , 
NN(
0, 
0, 
-1, 27.4199, 1, -1, 0.136336,-99) , 
9, 546.998, 1, 0, 0.483784,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0650651,-99) , 
0, 294.528, 1, 0, 0.479907,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0275768);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.486215,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0369457);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330553,-99) , 
7, 2.64232, 1, 0, 0.500012,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.150286,-99) , 
9, 546.998, 1, 0, 0.49686,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.072333,-99) , 
0, 294.528, 1, 0, 0.493106,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0494454);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428617,-99) , 
9, 156.154, 1, 0, 0.491408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.149496,-99) , 
9, 546.998, 1, 0, 0.488366,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0748516,-99) , 
0, 294.528, 1, 0, 0.484765,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0454253);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.477303,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0227838);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.52299, 1, -1, 0.495022,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.154239,-99) , 
9, 546.998, 1, 0, 0.492085,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0816921,-99) , 
0, 294.528, 1, 0, 0.488646,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0213045);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.500718,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.153708,-99) , 
9, 546.998, 1, 0, 0.497751,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0834177,-99) , 
0, 294.528, 1, 0, 0.49431,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0216621);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.489171,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0211103);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.500845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.156034,-99) , 
9, 546.998, 1, 0, 0.49794,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0867622,-99) , 
0, 294.528, 1, 0, 0.494585,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0210262);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.489488,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0207129);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.500861,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.158301,-99) , 
9, 546.998, 1, 0, 0.498015,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0901595,-99) , 
0, 294.528, 1, 0, 0.494744,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0205228);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.48974,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0202773);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.500849,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.160527,-99) , 
9, 546.998, 1, 0, 0.498061,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0935998,-99) , 
0, 294.528, 1, 0, 0.49487,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0200666);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.489968,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0198503);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.50083,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 391.147, 0, 0, 0.162718,-99) , 
9, 546.998, 1, 0, 0.498097,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.0970791,-99) , 
0, 294.528, 1, 0, 0.494984,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0196377);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.490182,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0194596);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.50081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.164879,-99) , 
9, 546.998, 1, 0, 0.49813,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.100596,-99) , 
0, 294.528, 1, 0, 0.495091,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.01924);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.52299, 1, -1, 0.495976,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 391.147, 0, 0, 0.164356,-99) , 
9, 546.998, 1, 0, 0.493348,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.10237,-99) , 
0, 294.528, 1, 0, 0.490382,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0190503);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.500786,-99) , 
NN(
0, 
0, 
-1, 27.4199, 1, -1, 0.163833,-99) , 
9, 546.998, 1, 0, 0.498133,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.104152,-99) , 
0, 294.528, 1, 0, 0.495166,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0188768);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.52299, 1, -1, 0.496054,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.166459,-99) , 
9, 546.998, 1, 0, 0.493474,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.105943,-99) , 
0, 294.528, 1, 0, 0.490578,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0186705);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.500773,-99) , 
NN(
0, 
0, 
-1, 391.147, 0, -1, 0.165939,-99) , 
9, 546.998, 1, 0, 0.498169,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.107744,-99) , 
0, 294.528, 1, 0, 0.495272,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0184901);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.52299, 1, -1, 0.496134,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 391.147, 0, 0, 0.168539,-99) , 
9, 546.998, 1, 0, 0.493602,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.109552,-99) , 
0, 294.528, 1, 0, 0.490773,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.018312);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.500757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.168018,-99) , 
9, 546.998, 1, 0, 0.4982,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.111369,-99) , 
0, 294.528, 1, 0, 0.49537,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0410561);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422901,-99) , 
4, 130.664, 0, 0, 0.496207,-99) , 
NN(
0, 
0, 
-1, 391.147, 0, -1, 0.1675,-99) , 
9, 546.998, 1, 0, 0.493697,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.113194,-99) , 
0, 294.528, 1, 0, 0.490932,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0330538);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.483479,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0234724);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.193529,-99) , 
9, 546.998, 1, 0, 0.499632,-99) , 
NN(
0, 
0, 
-1, 1.49621, 1, -1, 0.344376,-99) , 
7, 2.64232, 1, 0, 0.494378,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.120849,-99) , 
0, 294.528, 1, 0, 0.491737,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0271607);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.486423,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0135803);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.49321,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0183722);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190184,-99) , 
9, 546.998, 1, 0, 0.500681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499169,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.127839,-99) , 
0, 294.528, 1, 0, 0.496605,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0156662);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.492168,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0167567);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.195482,-99) , 
9, 546.998, 1, 0, 0.500071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498586,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.131683,-99) , 
0, 294.528, 1, 0, 0.496084,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0507553);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484576,-99) , 
5, 65.0336, 0, 0, 0.495942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.494481,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.133611,-99) , 
0, 294.528, 1, 0, 0.492035,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0248001);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.196062,-99) , 
9, 546.998, 1, 0, 0.504379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.50293,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.139596,-99) , 
0, 294.528, 1, 0, 0.50051,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0568279);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454123,-99) , 
6, 1.19697, 0, 0, 0.500699,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 27.4199, 1, 0, 0.195251,-99) , 
9, 546.998, 1, 0, 0.498496,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 225.799, 1, 0, 0.461914,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 142.734, 0, 0, 0.123618,-99) , 
6, 1.34533, 1, 0, 0.287057,-99) , 
7, 2.94735, 1, 0, 0.494512,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0264587);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.486774,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0132293);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.493386,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0170314);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.220595,-99) , 
11, 3.44448, 1, 0, 0.500403,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499025,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.142829,-99) , 
0, 294.528, 1, 0, 0.496693,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0148408);
  fForest.push_back( 
NN(
0, 
0, 
-1, 294.528, 1, -1, 0.49258,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0156853);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.226124,-99) , 
11, 3.44448, 1, 0, 0.499923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498567,-99) , 
NN(
0, 
0, 
-1, 230.623, 0, -1, 0.146775,-99) , 
0, 294.528, 1, 0, 0.49629,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0149993);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.492501,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0129931);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.197891,-99) , 
9, 546.998, 1, 0, 0.499276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.49781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.49625,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0138293);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.493086,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0132343);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.202183,-99) , 
9, 546.998, 1, 0, 0.49953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.496543,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0133634);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.493319,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0131297);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.206507,-99) , 
9, 546.998, 1, 0, 0.499608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.496659,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0130812);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.49346,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0129415);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.210835,-99) , 
9, 546.998, 1, 0, 0.49964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.49823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.49673,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.01285);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.493575,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0133696);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232285,-99) , 
11, 3.44448, 1, 0, 0.499661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.496788,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0129311);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.493535,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0125182);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.215607,-99) , 
9, 546.998, 1, 0, 0.499604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.49823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.496767,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0125711);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.493715,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0129885);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237483,-99) , 
11, 3.44448, 1, 0, 0.499659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.496857,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0162573);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.49992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.179805,-99) , 
6, 1.49621, 1, 0, 0.356124,-99) , 
7, 2.64232, 1, 0, 0.495122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.493696,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0397303);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454592,-99) , 
9, 130.129, 1, 0, 0.493204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 419.896, 0, 0, 0.20682,-99) , 
9, 546.998, 1, 0, 0.4912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.62744, 1, 0, 0.489791,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0300919);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.484959,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0338049);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446924,-99) , 
7, 1.67759, 1, 0, 0.495152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.493856,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.492478,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0257282);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.487139,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0128641);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.493568,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0112091);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.222189,-99) , 
9, 546.998, 1, 0, 0.499388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.496784,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0248517);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425031,-99) , 
2, 40.0204, 0, 0, 0.496622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.495374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.494047,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0220264);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.488989,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0110132);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.494494,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0116476);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.225838,-99) , 
9, 546.998, 1, 0, 0.499765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497247,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0111977);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.494401,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00818909);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.49969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497201,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.00963746);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495181,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.00884769);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.50006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497591,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00918267);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495409,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00895326);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497704,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.00900788);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495496,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0120968);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.230548,-99) , 
9, 546.998, 1, 0, 0.500175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497748,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0104173);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.494792,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00810211);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497396,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0221895);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494378,-99) , 
1, 116.819, 0, 0, 0.497775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.496623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.495397,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0144669);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.503054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.501902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.500676,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.00723346);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497107,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.00935652);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495322,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0082348);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.49886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497661,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00874295);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495629,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0115793);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.235391,-99) , 
9, 546.998, 1, 0, 0.500122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497814,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0100351);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.494983,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.00768321);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497491,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.00881079);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495595,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.00819172);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497797,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.00845009);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495775,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.00826834);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497887,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.00830799);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495846,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0082369);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497923,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.00822184);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495889,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.00817905);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497945,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0228191);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424541,-99) , 
6, 2.99194, 1, 0, 0.498117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.497054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.495925,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0177899);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.491106,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.00889497);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495553,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0107057);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239562,-99) , 
9, 546.998, 1, 0, 0.499923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497776,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0096877);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495156,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.00707793);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497578,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.00834098);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.49583,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.00766029);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497915,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.00795568);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496022,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.00776146);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.49909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498011,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.00781337);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496093,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.00774208);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498047,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.00773298);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496134,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.00769301);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498067,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.00766887);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496166,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0107495);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.244087,-99) , 
9, 546.998, 1, 0, 0.500128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498083,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.00909868);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495451,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.00683787);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497725,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.00792965);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496035,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.00733909);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498018,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0436824);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482992,-99) , 
10, 1.19659, 0, 0, 0.498199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.497232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.496203,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.0128986);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.23939,-99) , 
9, 546.998, 1, 0, 0.501215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.500263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.499249,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0164779);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.501034,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198709,-99) , 
6, 1.49621, 1, 0, 0.378337,-99) , 
7, 2.64232, 1, 0, 0.497091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.49609,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0157684);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.492116,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.0078842);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496058,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0101383);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.243404,-99) , 
9, 546.998, 1, 0, 0.499945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498029,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0089097);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495545,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.00993352);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501385,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.263044,-99) , 
11, 3.44448, 1, 0, 0.49967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497773,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.00931335);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495343,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.0060642);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497672,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.00765652);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496172,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.00990911);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.247585,-99) , 
9, 546.998, 1, 0, 0.499954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498086,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.00868489);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495658,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.00623282);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497829,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.00742614);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496287,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0067906);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498143,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.00707296);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496464,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.00689502);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.49917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498232,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.00694827);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496526,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.00688578);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498263,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.0068816);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496559,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.00684841);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500856,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.49828,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.0186682);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623013,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49529,-99) , 
1, 116.819, 0, 0, 0.498374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.497504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.496585,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.012216);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.502816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.501947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.501028,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.00920171);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.251746,-99) , 
9, 546.998, 1, 0, 0.499771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498005,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.0145192);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500387,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.205115,-99) , 
6, 1.49621, 1, 0, 0.382994,-99) , 
7, 2.64232, 1, 0, 0.496648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.495749,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.0666906);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425711,-99) , 
2, 53.0012, 0, 0, 0.498727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.747052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39174,-99) , 
2, 42.7764, 1, 0, 0.421864,-99) , 
4, 407.385, 1, 0, 0.493133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.62744, 1, 0, 0.492243,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.0442246);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484854,-99) , 
1, 116.819, 0, 0, 0.487902,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.20006,-99) , 
6, 1.49621, 1, 0, 0.372915,-99) , 
7, 2.64232, 1, 0, 0.484246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.483392,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.0270771);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500217,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.735609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.243632,-99) , 
4, 153.838, 1, 0, 0.388554,-99) , 
6, 0.299486, 0, 0, 0.496179,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 133.512, 1, 0, 0.419055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 16.2889, 0, 0, 0.330287,-99) , 
7, 2.94735, 1, 0, 0.493521,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.0355516);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.90374, 1, -1, 0.493468,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.730309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.248656,-99) , 
4, 153.838, 1, 0, 0.390593,-99) , 
6, 0.299486, 0, 0, 0.489772,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 133.512, 1, 0, 0.414551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 16.2889, 0, 0, 0.327483,-99) , 
7, 2.94735, 1, 0, 0.487184,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.0295248);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.502356,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.72325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.255357,-99) , 
4, 153.838, 1, 0, 0.393313,-99) , 
6, 0.299486, 0, 0, 0.49847,-99) , 
NN(
0, 
0, 
-1, 16.2889, 0, -1, 0.323758,-99) , 
7, 2.94735, 1, 0, 0.4957,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.0221357);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.488934,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.0110679);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.494466,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.0159844);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.502003,-99) , 
NN(
0, 
0, 
-1, 46.9855, 0, -1, 0.376427,-99) , 
7, 2.64232, 1, 0, 0.498072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497233,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.0129803);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.49351,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.0140402);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.501264,-99) , 
NN(
0, 
0, 
-1, 46.9855, 0, -1, 0.38325,-99) , 
7, 2.64232, 1, 0, 0.497582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.496755,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.0130327);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.493484,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.00651637);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496742,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.00926978);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.275502,-99) , 
11, 3.44448, 1, 0, 0.499968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498371,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.00780053);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.4961,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.00513664);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.498858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.49805,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.00644552);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496777,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.0057622);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.499963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498389,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.00607813);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.496961,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.0058931);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.49928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.49848,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.00595945);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.49702,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.00589989);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.49851,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.00590363);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.497048,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.00587578);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498524,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.00586392);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.497068,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.00585549);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 875.197, 1, 0, 0.500072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.49932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498534,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.00583413);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.497083,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.00582207);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.50007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498541,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.00580281);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.497099,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.00579845);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 875.197, 1, 0, 0.500069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498549,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.00577555);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.497112,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.00576469);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.500067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498556,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.00574532);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.497127,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.00574137);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 875.197, 1, 0, 0.500066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498564,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.0110807);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.736704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499931,-99) , 
8, 404.189, 0, 0, 0.501317,-99) , 
NN(
0, 
0, 
-1, 46.9855, 0, -1, 0.391235,-99) , 
7, 2.64232, 1, 0, 0.497904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497141,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.00831085);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 875.197, 1, 0, 0.501374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.500643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.499879,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.014523);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 3.90374, 1, 0, 0.501982,-99) , 
NN(
0, 
0, 
-1, 46.9855, 0, -1, 0.392061,-99) , 
7, 2.64232, 1, 0, 0.498576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497819,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.0111348);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.494433,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.00556739);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.497216,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.00563278);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 875.197, 1, 0, 0.500069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498608,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.00614079);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.281478,-99) , 
11, 3.44448, 1, 0, 0.498665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.497954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.497212,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.00858795);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.495706,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.00429397);
  fForest.push_back( 
NN(
0, 
0, 
-1, 349.433, 1, -1, 0.497853,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.00617759);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 875.197, 1, 0, 0.500371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52299, 1, 0, 0.499664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 349.433, 1, 0, 0.498926,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_mm_ge2j::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_mm_ge2j::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
