// Class: ReadBDT_em_ge2j
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_em_ge2j
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.30/05       [335365]
Creator        : gerbaudo
Date           : Tue Jan 14 18:50:26 2014
Host           : Linux lxbuild147.cern.ch 2.6.18-194.26.1.el5 #1 SMP Wed Nov 10 09:51:11 CET 2010 i686 i686 i386 GNU/Linux
Dir            : /data7/atlas/gerbaudo/wh/Susy2013_Nt_01_04_dev/SusyTest0/run
Training events: 91446
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "50" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "4" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "91446" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
mll                           mll                           mll                           mll                                                             'F'    [19.3989677429,1615.65820312]
mtmin                         mtmin                         mtmin                         mtmin                                                           'F'    [0.00109364616219,380.675872803]
mtmax                         mtmax                         mtmax                         mtmax                                                           'F'    [1.19316351414,2005.2019043]
mtllmet                       mtllmet                       mtllmet                       mtllmet                                                         'F'    [0.00353958806954,1910.56164551]
ht                            ht                            ht                            ht                                                              'F'    [76.5024337769,2517.2277832]
metrel                        metrel                        metrel                        metrel                                                          'F'    [0.000532302539796,407.61315918]
dphill                        dphill                        dphill                        dphill                                                          'F'    [8.96453857422e-05,3.14158797264]
detall                        detall                        detall                        detall                                                          'F'    [2.02655792236e-06,4.80321407318]
mt2j                          mt2j                          mt2j                          mt2j                                                            'F'    [0,1188.41894531]
mljj                          mljj                          mljj                          mljj                                                            'F'    [0,2671.67578125]
dphijj                        dphijj                        dphijj                        dphijj                                                          'F'    [0,3.14155697823]
detajj                        detajj                        detajj                        detajj                                                          'F'    [0,4.8568649292]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_em_ge2jNode
   
#ifndef BDT_em_ge2jNode__def
#define BDT_em_ge2jNode__def
   
class BDT_em_ge2jNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_em_ge2jNode ( BDT_em_ge2jNode* left,BDT_em_ge2jNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_em_ge2jNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_em_ge2jNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_em_ge2jNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_em_ge2jNode*   fLeft;     // pointer to the left daughter node
   BDT_em_ge2jNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_em_ge2jNode::~BDT_em_ge2jNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_em_ge2jNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_em_ge2jNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_em_ge2j : public IClassifierReader {

 public:

   // constructor
   ReadBDT_em_ge2j( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_em_ge2j" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mll", "mtmin", "mtmax", "mtllmet", "ht", "metrel", "dphill", "detall", "mt2j", "mljj", "dphijj", "detajj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 19.3989677429199;
      fVmax[0] = 1615.658203125;
      fVmin[1] = 0.00109364616218954;
      fVmax[1] = 380.675872802734;
      fVmin[2] = 1.19316351413727;
      fVmax[2] = 2005.20190429688;
      fVmin[3] = 0.00353958806954324;
      fVmax[3] = 1910.56164550781;
      fVmin[4] = 76.5024337768555;
      fVmax[4] = 2517.22778320312;
      fVmin[5] = 0.000532302539795637;
      fVmax[5] = 407.613159179688;
      fVmin[6] = 8.96453857421875e-05;
      fVmax[6] = 3.14158797264099;
      fVmin[7] = 2.02655792236328e-06;
      fVmax[7] = 4.80321407318115;
      fVmin[8] = 0;
      fVmax[8] = 1188.4189453125;
      fVmin[9] = 0;
      fVmax[9] = 2671.67578125;
      fVmin[10] = 0;
      fVmax[10] = 3.14155697822571;
      fVmin[11] = 0;
      fVmax[11] = 4.85686492919922;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_em_ge2j() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_em_ge2jNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_em_ge2j::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_em_ge2jNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_em_ge2jNode*)current->GetRight();
         else current=(BDT_em_ge2jNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_em_ge2j::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.80941582367016);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.149598, 0, -1, 0.0261138,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.904708);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1.14362, 1, -1, 0.140709,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.459425);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351316,-99) , 
0, 66.3253, 1, 0, 0.420745,-99) , 
NN(
0, 
0, 
-1, 175.558, 0, -1, 0.2626,-99) , 
10, 0.149598, 0, 0, 0.3383,-99) , 
NN(
0, 
0, 
-1, 2.01496, 1, -1, 0.198217,-99) , 
7, 1.14362, 1, 0, 0.288084,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.294408);
  fForest.push_back( 
NN(
0, 
0, 
-1, 192.727, 0, -1, 0.356906,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.218415);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402594,-99) , 
9, 226.129, 1, 0, 0.516714,-99) , 
NN(
0, 
0, 
-1, 2.51601, 1, -1, 0.354655,-99) , 
7, 1.37235, 1, 0, 0.477927,-99) , 
NN(
0, 
0, 
-1, 159.517, 0, -1, 0.328938,-99) , 
4, 192.727, 0, 0, 0.426925,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.203612);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430983,-99) , 
9, 153.066, 1, 0, 0.505057,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383078,-99) , 
5, 60.6499, 0, 0, 0.419001,-99) , 
10, 0.74799, 0, 0, 0.452882,-99) , 
NN(
0, 
0, 
-1, 273.746, 1, -1, 0.26127,-99) , 
7, 2.05852, 1, 0, 0.435268,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.128253);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4831,-99) , 
2, 129.332, 0, 0, 0.50087,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42005,-99) , 
6, 0.748233, 1, 0, 0.433912,-99) , 
8, 56.5914, 0, 0, 0.467851,-99) , 
NN(
0, 
0, 
-1, 273.746, 1, -1, 0.302428,-99) , 
7, 2.05852, 1, 0, 0.45308,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0866424);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315123,-99) , 
9, 529.821, 1, 0, 0.513003,-99) , 
NN(
0, 
0, 
-1, 210.726, 1, -1, 0.453011,-99) , 
8, 56.5914, 0, 0, 0.483384,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.267584,-99) , 
2, 166.355, 0, 0, 0.295111,-99) , 
NN(
0, 
0, 
-1, 2.99154, 0, -1, 0.0405092,-99) , 
0, 289.628, 1, 0, 0.253228,-99) , 
7, 2.51597, 1, 0, 0.47412,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0911396);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489509,-99) , 
7, 0.686137, 1, 0, 0.549325,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4732,-99) , 
6, 0.448875, 1, 0, 0.478315,-99) , 
1, 90.6379, 0, 0, 0.488064,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341439,-99) , 
5, 78.754, 0, 0, 0.373121,-99) , 
NN(
0, 
0, 
-1, 2.99154, 0, -1, 0.0802673,-99) , 
0, 273.746, 1, 0, 0.33775,-99) , 
7, 2.05852, 1, 0, 0.474998,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0876406);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493098,-99) , 
8, 35.3946, 0, 0, 0.519345,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446488,-99) , 
7, 0.490196, 1, 0, 0.475361,-99) , 
9, 127.223, 1, 0, 0.504988,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353217,-99) , 
5, 65.6289, 0, 0, 0.388161,-99) , 
NN(
0, 
0, 
-1, 2.99154, 0, -1, 0.0872582,-99) , 
0, 273.746, 1, 0, 0.352625,-99) , 
7, 2.05852, 1, 0, 0.491906,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0754575);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479659,-99) , 
9, 127.223, 1, 0, 0.514646,-99) , 
NN(
0, 
0, 
-1, 198.267, 1, -1, 0.430628,-99) , 
7, 1.91692, 1, 0, 0.508592,-99) , 
NN(
0, 
0, 
-1, 289.628, 1, -1, 0.292197,-99) , 
7, 2.51597, 1, 0, 0.500304,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0703502);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48889,-99) , 
0, 95.4113, 1, 0, 0.518912,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317333,-99) , 
3, 24.1775, 0, 0, 0.473249,-99) , 
4, 192.727, 0, 0, 0.503858,-99) , 
NN(
0, 
0, 
-1, 289.628, 1, -1, 0.308044,-99) , 
7, 2.51597, 1, 0, 0.496454,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0661453);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49828,-99) , 
6, 2.5432, 0, 0, 0.518489,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389967,-99) , 
4, 148.448, 0, 0, 0.460803,-99) , 
4, 192.727, 0, 0, 0.499469,-99) , 
NN(
0, 
0, 
-1, 289.628, 1, -1, 0.323238,-99) , 
7, 2.51597, 1, 0, 0.49288,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.087409);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415496,-99) , 
0, 203.997, 1, 0, 0.527273,-99) , 
NN(
0, 
0, 
-1, 2.05884, 1, -1, 0.368296,-99) , 
0, 247.436, 1, 0, 0.518726,-99) , 
NN(
0, 
0, 
-1, 24.1775, 0, -1, 0.449752,-99) , 
4, 192.727, 0, 0, 0.495791,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0329305);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49828,-99) , 
7, 0.71763, 1, 0, 0.581505,-99) , 
NN(
0, 
0, 
-1, 890.078, 1, -1, 0.492429,-99) , 
1, 108.765, 0, 0, 0.496785,-99) , 
NN(
0, 
0, 
-1, 289.628, 1, -1, 0.347091,-99) , 
7, 2.51597, 1, 0, 0.491285,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0274314);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 118.261, 0, 1, 0.548258,-99) , 
NN(
0, 
0, 
-1, 508.891, 1, -1, 0.497582,-99) , 
1, 90.6379, 0, 0, 0.504541,-99) , 
NN(
0, 
0, 
-1, 289.628, 1, -1, 0.354591,-99) , 
7, 2.51597, 1, 0, 0.499056,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.049373);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486997,-99) , 
7, 1.19808, 1, 0, 0.511375,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.700927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323787,-99) , 
1, 117.222, 0, 0, 0.357554,-99) , 
9, 508.891, 1, 0, 0.509517,-99) , 
NN(
0, 
0, 
-1, 289.628, 1, -1, 0.360893,-99) , 
7, 2.51597, 1, 0, 0.5041,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0557092);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447872,-99) , 
3, 34.9644, 0, 0, 0.504164,-99) , 
NN(
0, 
0, 
-1, 91.0078, 1, -1, 0.269739,-99) , 
4, 890.078, 1, 0, 0.50311,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 0.693838, 1, 0, 0.490735,-99) , 
NN(
0, 
0, 
-1, 232.96, 1, -1, 0.225754,-99) , 
6, 2.54291, 0, 0, 0.337943,-99) , 
7, 2.74469, 1, 0, 0.499272,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0288928);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492563,-99) , 
1, 108.765, 0, 0, 0.495544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.495093,-99) , 
NN(
0, 
0, 
-1, 289.628, 1, -1, 0.370522,-99) , 
7, 2.51597, 1, 0, 0.490606,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0310454);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493334,-99) , 
10, 1.19678, 0, 0, 0.502068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.501618,-99) , 
NN(
0, 
0, 
-1, 289.628, 1, -1, 0.377286,-99) , 
7, 2.51597, 1, 0, 0.497154,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0250127);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 430.104, 1, 0, 0.505258,-99) , 
NN(
0, 
0, 
-1, 1.69776, 1, -1, 0.358345,-99) , 
9, 508.891, 1, 0, 0.503502,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595371,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 0.875569, 1, 0, 0.508601,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.176418,-99) , 
5, 81.9369, 0, 0, 0.252369,-99) , 
3, 52.4527, 1, 0, 0.353455,-99) , 
7, 2.74469, 1, 0, 0.500081,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0253883);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473707,-99) , 
11, 1.37743, 1, 0, 0.498705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.49827,-99) , 
NN(
0, 
0, 
-1, 289.628, 1, -1, 0.382355,-99) , 
7, 2.51597, 1, 0, 0.494135,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0500735);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.109573,-99) , 
6, 1.93817, 1, 0, 0.533803,-99) , 
NN(
0, 
0, 
-1, 1.34645, 0, -1, 0.485093,-99) , 
0, 51.975, 1, 0, 0.494537,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.125612,-99) , 
1, 15.5307, 0, 0, 0.482023,-99) , 
NN(
0, 
0, 
-1, 120.974, 1, -1, 0.165817,-99) , 
7, 2.05884, 1, 0, 0.383049,-99) , 
0, 247.436, 1, 0, 0.490498,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0487537);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490267,-99) , 
6, 2.09446, 0, 0, 0.525533,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421425,-99) , 
0, 127.977, 1, 0, 0.490923,-99) , 
2, 113.128, 0, 0, 0.502278,-99) , 
NN(
0, 
0, 
-1, 2.05884, 1, -1, 0.378931,-99) , 
0, 247.436, 1, 0, 0.497834,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0561195);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421624,-99) , 
4, 475.544, 1, 0, 0.525786,-99) , 
NN(
0, 
0, 
-1, 149.693, 1, -1, 0.482237,-99) , 
2, 113.128, 0, 0, 0.496515,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 2.31836, 0, 0, 0.483606,-99) , 
NN(
0, 
0, 
-1, 120.974, 1, -1, 0.179942,-99) , 
7, 2.05884, 1, 0, 0.390471,-99) , 
0, 247.436, 1, 0, 0.492713,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0210414);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384432,-99) , 
4, 636.493, 1, 0, 0.502701,-99) , 
NN(
0, 
0, 
-1, 247.566, 0, -1, 0.113889,-99) , 
11, 4.16303, 1, 0, 0.502125,-99) , 
NN(
0, 
0, 
-1, 2.24418, 0, -1, 0.385132,-99) , 
0, 247.436, 1, 0, 0.49795,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0323498);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480125,-99) , 
9, 113.065, 1, 0, 0.497595,-99) , 
NN(
0, 
0, 
-1, 247.566, 0, -1, 0.116029,-99) , 
11, 4.16303, 1, 0, 0.497034,-99) , 
NN(
0, 
0, 
-1, 2.24418, 0, -1, 0.390126,-99) , 
0, 247.436, 1, 0, 0.493228,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0299101);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475733,-99) , 
4, 188.501, 0, 0, 0.495434,-99) , 
NN(
0, 
0, 
-1, 247.566, 0, -1, 0.119389,-99) , 
11, 4.16303, 1, 0, 0.494887,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.267639,-99) , 
7, 2.03431, 1, 0, 0.444299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 2.24418, 0, 0, 0.39785,-99) , 
0, 247.436, 1, 0, 0.491443,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0326189);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47781,-99) , 
1, 54.3832, 1, 0, 0.492783,-99) , 
NN(
0, 
0, 
-1, 247.566, 0, -1, 0.122569,-99) , 
11, 4.16303, 1, 0, 0.492251,-99) , 
NN(
0, 
0, 
-1, 2.24418, 0, -1, 0.394903,-99) , 
0, 247.436, 1, 0, 0.488805,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0366784);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487066,-99) , 
0, 41.1163, 1, 0, 0.491879,-99) , 
NN(
0, 
0, 
-1, 247.566, 0, -1, 0.126121,-99) , 
11, 4.16303, 1, 0, 0.491359,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280072,-99) , 
7, 2.03431, 1, 0, 0.448452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 2.24418, 0, 0, 0.402724,-99) , 
0, 247.436, 1, 0, 0.48823,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0101132);
  fForest.push_back( 
NN(
0, 
0, 
-1, 247.436, 1, -1, 0.494944,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.012076);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.58, 1, 0, 0.501486,-99) , 
NN(
0, 
0, 
-1, 247.566, 0, -1, 0.131369,-99) , 
11, 4.16303, 1, 0, 0.500969,-99) , 
NN(
0, 
0, 
-1, 2.24418, 0, -1, 0.40149,-99) , 
0, 247.436, 1, 0, 0.497472,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.010647);
  fForest.push_back( 
NN(
0, 
0, 
-1, 247.436, 1, -1, 0.494677,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0111311);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.58, 1, 0, 0.501133,-99) , 
NN(
0, 
0, 
-1, 247.566, 0, -1, 0.133984,-99) , 
11, 4.16303, 1, 0, 0.500624,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2943,-99) , 
7, 2.03431, 1, 0, 0.451754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 2.24418, 0, 0, 0.406962,-99) , 
0, 247.436, 1, 0, 0.497338,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0107446);
  fForest.push_back( 
NN(
0, 
0, 
-1, 247.436, 1, -1, 0.494628,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0107989);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.58, 1, 0, 0.50104,-99) , 
NN(
0, 
0, 
-1, 247.566, 0, -1, 0.136542,-99) , 
11, 4.16303, 1, 0, 0.500539,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298864,-99) , 
7, 2.03431, 1, 0, 0.452944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 2.24418, 0, 0, 0.408432,-99) , 
0, 247.436, 1, 0, 0.497314,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0106325);
  fForest.push_back( 
NN(
0, 
0, 
-1, 247.436, 1, -1, 0.494684,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0105791);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.146491,-99) , 
11, 4.16303, 1, 0, 0.500867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.58, 1, 0, 0.500508,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303374,-99) , 
7, 2.03431, 1, 0, 0.454149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 2.24418, 0, 0, 0.409907,-99) , 
0, 247.436, 1, 0, 0.497342,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0142486);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440571,-99) , 
0, 193.138, 1, 0, 0.498229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.58, 1, 0, 0.497874,-99) , 
NN(
0, 
0, 
-1, 2.24418, 0, -1, 0.408831,-99) , 
0, 247.436, 1, 0, 0.494765,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0166925);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1017.58, 1, -1, 0.494646,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308646,-99) , 
7, 2.03431, 1, 0, 0.456278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 2.24418, 0, 0, 0.412279,-99) , 
0, 247.436, 1, 0, 0.491774,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.00850846);
  fForest.push_back( 
NN(
0, 
0, 
-1, 247.436, 1, -1, 0.495746,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0109962);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.149311,-99) , 
11, 4.16303, 1, 0, 0.501297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.58, 1, 0, 0.500946,-99) , 
NN(
0, 
0, 
-1, 2.24418, 0, -1, 0.412633,-99) , 
0, 247.436, 1, 0, 0.497873,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.00934935);
  fForest.push_back( 
NN(
0, 
0, 
-1, 247.436, 1, -1, 0.495325,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.00983052);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.151914,-99) , 
11, 4.16303, 1, 0, 0.500892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.58, 1, 0, 0.500546,-99) , 
NN(
0, 
0, 
-1, 2.24418, 0, -1, 0.417573,-99) , 
0, 247.436, 1, 0, 0.497663,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.00923035);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.495385,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.00836168);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.500586,-99) , 
NN(
0, 
0, 
-1, 241.948, 1, -1, 0.412059,-99) , 
7, 2.59181, 1, 0, 0.498148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.497692,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0085526);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.495724,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.00820836);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417471,-99) , 
7, 2.59181, 1, 0, 0.49872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.498313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.497862,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.00814192);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.495929,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.00793869);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421453,-99) , 
7, 2.59181, 1, 0, 0.498816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.498413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.497965,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.00780994);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.496095,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.00390497);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498048,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.00320975);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.149104,-99) , 
11, 4.16303, 1, 0, 0.499869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499024,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.00354789);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498226,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.00336837);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.149963,-99) , 
11, 4.16303, 1, 0, 0.499955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499113,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.00344822);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498276,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.00339816);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.150834,-99) , 
11, 4.16303, 1, 0, 0.499977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.49958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499138,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.00341322);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498293,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.00339569);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.151709,-99) , 
11, 4.16303, 1, 0, 0.499983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499147,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.00808458);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425542,-99) , 
7, 2.59181, 1, 0, 0.499137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.498741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.498303,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.00720274);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.496399,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.00360137);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498199,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.00325602);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.152564,-99) , 
11, 4.16303, 1, 0, 0.499927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.4991,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.00341924);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.49829,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.00332771);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153429,-99) , 
11, 4.16303, 1, 0, 0.49997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499145,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.00336384);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498318,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.00333605);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.1543,-99) , 
11, 4.16303, 1, 0, 0.499981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499159,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.00334032);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.49833,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.00332856);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.155173,-99) , 
11, 4.16303, 1, 0, 0.499984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499165,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.00332486);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498338,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.00331715);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.156047,-99) , 
11, 4.16303, 1, 0, 0.499985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499169,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.00331148);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498344,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.00330483);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.156922,-99) , 
11, 4.16303, 1, 0, 0.499986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.4996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499172,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0032987);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498351,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.00329233);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.157798,-99) , 
11, 4.16303, 1, 0, 0.499986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499175,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.00328612);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498357,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.00327986);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.158674,-99) , 
11, 4.16303, 1, 0, 0.499987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499178,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.00327365);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498363,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.00326745);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.159551,-99) , 
11, 4.16303, 1, 0, 0.499987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499182,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.00326128);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498369,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.00325512);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.160428,-99) , 
11, 4.16303, 1, 0, 0.499988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499185,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.00324899);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498376,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.00324287);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.161306,-99) , 
11, 4.16303, 1, 0, 0.499988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499188,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.00323678);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498382,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0032307);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162185,-99) , 
11, 4.16303, 1, 0, 0.499989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499191,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00860714);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435938,-99) , 
0, 247.436, 1, 0, 0.499183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.498806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.498388,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0072245);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.496388,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.00361225);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498194,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00299977);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162981,-99) , 
11, 4.16303, 1, 0, 0.499886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499097,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00329763);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498351,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0031395);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.163842,-99) , 
11, 4.16303, 1, 0, 0.499962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499176,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.00320981);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498395,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.00316572);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.164714,-99) , 
11, 4.16303, 1, 0, 0.499982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.49961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499198,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00317897);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498411,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.00316352);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.165589,-99) , 
11, 4.16303, 1, 0, 0.499987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499205,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.00316248);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498419,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.00315425);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.166464,-99) , 
11, 4.16303, 1, 0, 0.499989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499209,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.00314964);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498425,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.00314325);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167341,-99) , 
11, 4.16303, 1, 0, 0.499989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499213,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00758247);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430171,-99) , 
7, 2.59181, 1, 0, 0.499205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.498839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.498431,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.00671072);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.496645,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.00335536);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498322,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.00300071);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.168193,-99) , 
11, 4.16303, 1, 0, 0.49993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499161,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.00316982);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498415,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0030766);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.169058,-99) , 
11, 4.16303, 1, 0, 0.499974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499208,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.00311481);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498443,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.0030872);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.16993,-99) , 
11, 4.16303, 1, 0, 0.499985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499221,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0030926);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498454,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.00308149);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500385,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.170803,-99) , 
11, 4.16303, 1, 0, 0.499988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499227,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.00307867);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498461,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.00307172);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.171677,-99) , 
11, 4.16303, 1, 0, 0.49999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.49963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.49923,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.00306687);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498467,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.003061);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.172552,-99) , 
11, 4.16303, 1, 0, 0.49999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499233,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.00305566);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498472,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.00305008);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.173427,-99) , 
11, 4.16303, 1, 0, 0.499991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499236,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.00304465);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498478,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.00303917);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.174303,-99) , 
11, 4.16303, 1, 0, 0.499991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499239,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.00303373);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498483,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0030283);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.175178,-99) , 
11, 4.16303, 1, 0, 0.499992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499242,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0030229);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498489,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.0030175);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.176054,-99) , 
11, 4.16303, 1, 0, 0.499992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499244,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.00301213);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498494,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.00300677);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.176931,-99) , 
11, 4.16303, 1, 0, 0.499993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499247,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.00300142);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498499,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.00299609);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.177807,-99) , 
11, 4.16303, 1, 0, 0.499993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.49925,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.00299078);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498505,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.00298549);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.178684,-99) , 
11, 4.16303, 1, 0, 0.499993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499252,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.0122676);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496768,-99) , 
1, 108.765, 0, 0, 0.499249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.498899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.49851,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0132162);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442729,-99) , 
0, 247.436, 1, 0, 0.502019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.50167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.501281,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.00358224);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498209,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.00263617);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.179541,-99) , 
11, 4.16303, 1, 0, 0.499834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499104,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.00310227);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498449,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.00286107);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.180388,-99) , 
11, 4.16303, 1, 0, 0.499952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499224,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.00297417);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498513,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.00290983);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.181252,-99) , 
11, 4.16303, 1, 0, 0.499982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499256,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.00293438);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498533,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.00291443);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.182121,-99) , 
11, 4.16303, 1, 0, 0.49999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499266,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0029168);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498542,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.00290801);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.182991,-99) , 
11, 4.16303, 1, 0, 0.499992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.49965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499271,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.00290483);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498548,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.00289886);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183862,-99) , 
11, 4.16303, 1, 0, 0.499993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499274,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.00706689);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434871,-99) , 
7, 2.59181, 1, 0, 0.49927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.49893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.498553,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.00622552);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.496887,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.00311276);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498444,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.00276058);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.184705,-99) , 
11, 4.16303, 1, 0, 0.499934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499222,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.00292954);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498535,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0028375);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.185564,-99) , 
11, 4.16303, 1, 0, 0.499978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499268,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.00287621);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498562,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.00284946);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.186429,-99) , 
11, 4.16303, 1, 0, 0.499989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499281,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.00285551);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498572,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.00284515);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.187296,-99) , 
11, 4.16303, 1, 0, 0.499992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499286,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.00284304);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498578,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.00283681);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.188163,-99) , 
11, 4.16303, 1, 0, 0.499993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.49966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499289,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.0219496);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491594,-99) , 
10, 1.04719, 0, 0, 0.499286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.498953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.498584,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.00479);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.189465,-99) , 
11, 4.16303, 1, 0, 0.500979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.500648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.500282,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.0206274);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48365,-99) , 
5, 15.1628, 0, 0, 0.499784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.49909,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.00590191);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.497049,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.00295096);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498525,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.00269869);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.189516,-99) , 
11, 4.16303, 1, 0, 0.499946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499262,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.00281802);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498591,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.00275126);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190365,-99) , 
11, 4.16303, 1, 0, 0.499977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499295,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.00277772);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498611,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.00275751);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.191218,-99) , 
11, 4.16303, 1, 0, 0.499986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499306,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.0027607);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.49862,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.00275219);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.192073,-99) , 
11, 4.16303, 1, 0, 0.499988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.49931,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.00274955);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498625,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.00220178);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.499989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499313,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.00247174);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498764,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.00233236);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499382,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.0023979);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498801,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.00290678);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.192981,-99) , 
11, 4.16303, 1, 0, 0.500074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499401,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.0026451);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498677,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.00222993);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.50001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499339,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.00243356);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498783,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.00232744);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499392,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.00237639);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498812,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.00234772);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499406,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.00235791);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498821,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.00289387);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.193888,-99) , 
11, 4.16303, 1, 0, 0.500077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499411,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.00261872);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498691,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.00221105);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.50001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499345,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.00241101);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498794,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.0023068);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499397,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.00235486);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498823,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.00232671);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.49976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499411,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.00233672);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498832,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.00232764);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499416,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.00232812);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498836,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.00287027);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.194791,-99) , 
11, 4.16303, 1, 0, 0.500077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499418,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.00259214);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498704,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.00218476);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499352,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.00238466);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498808,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.00228057);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499404,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.00232866);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498836,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.00230059);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499418,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.00231065);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498845,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.00284729);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.19569,-99) , 
11, 4.16303, 1, 0, 0.500075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499422,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.00257201);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498714,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.00216403);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1238.75, 1, 0, 0.500008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 1017.78, 1, 0, 0.499699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.88832, 1, 0, 0.499357,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.00236429);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.88832, 1, -1, 0.498818,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_em_ge2j::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_em_ge2j::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
