// Class: ReadBDT_mm_eq1j
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_mm_eq1j
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.30/05       [335365]
Creator        : gerbaudo
Date           : Tue Jan 14 18:33:10 2014
Host           : Linux lxbuild147.cern.ch 2.6.18-194.26.1.el5 #1 SMP Wed Nov 10 09:51:11 CET 2010 i686 i686 i386 GNU/Linux
Dir            : /data7/atlas/gerbaudo/wh/Susy2013_Nt_01_04_dev/SusyTest0/run
Training events: 7898
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "50" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "7898" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
mll                           mll                           mll                           mll                                                             'F'    [20.001121521,817.479248047]
mtmin                         mtmin                         mtmin                         mtmin                                                           'F'    [0.00879779178649,224.879486084]
mtmax                         mtmax                         mtmax                         mtmax                                                           'F'    [2.14877462387,726.309265137]
mtllmet                       mtllmet                       mtllmet                       mtllmet                                                         'F'    [0.0262490268797,717.774719238]
ht                            ht                            ht                            ht                                                              'F'    [63.8003120422,1727.81494141]
metrel                        metrel                        metrel                        metrel                                                          'F'    [0.00135941198096,309.39465332]
dphill                        dphill                        dphill                        dphill                                                          'F'    [0.000883460044861,3.1412062645]
detall                        detall                        detall                        detall                                                          'F'    [0.000212788581848,4.76091098785]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_mm_eq1jNode
   
#ifndef BDT_mm_eq1jNode__def
#define BDT_mm_eq1jNode__def
   
class BDT_mm_eq1jNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_mm_eq1jNode ( BDT_mm_eq1jNode* left,BDT_mm_eq1jNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_mm_eq1jNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_mm_eq1jNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_mm_eq1jNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_mm_eq1jNode*   fLeft;     // pointer to the left daughter node
   BDT_mm_eq1jNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_mm_eq1jNode::~BDT_mm_eq1jNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_mm_eq1jNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_mm_eq1jNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_mm_eq1j : public IClassifierReader {

 public:

   // constructor
   ReadBDT_mm_eq1j( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_mm_eq1j" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mll", "mtmin", "mtmax", "mtllmet", "ht", "metrel", "dphill", "detall" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 20.0011215209961;
      fVmax[0] = 817.479248046875;
      fVmin[1] = 0.00879779178649187;
      fVmax[1] = 224.879486083984;
      fVmin[2] = 2.14877462387085;
      fVmax[2] = 726.309265136719;
      fVmin[3] = 0.0262490268796682;
      fVmax[3] = 717.774719238281;
      fVmin[4] = 63.8003120422363;
      fVmax[4] = 1727.81494140625;
      fVmin[5] = 0.00135941198095679;
      fVmax[5] = 309.394653320312;
      fVmin[6] = 0.00088346004486084;
      fVmax[6] = 3.14120626449585;
      fVmin[7] = 0.000212788581848145;
      fVmax[7] = 4.760910987854;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_mm_eq1j() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_mm_eq1jNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_mm_eq1j::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_mm_eq1jNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_mm_eq1jNode*)current->GetRight();
         else current=(BDT_mm_eq1jNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_mm_eq1j::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.60904301969276);
  fForest.push_back( 
NN(
0, 
0, 
-1, 105.6, 0, -1, 0.0384908,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.833052);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249926,-99) , 
7, 1.74851, 1, 0, 0.508001,-99) , 
NN(
0, 
0, 
-1, 1.19334, 1, -1, 0.350229,-99) , 
5, 73.7859, 0, 0, 0.40559,-99) , 
NN(
0, 
0, 
-1, 143.039, 0, -1, 0.102346,-99) , 
2, 105.6, 0, 0, 0.166722,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.515746);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378284,-99) , 
5, 73.7859, 1, 0, 0.490658,-99) , 
NN(
0, 
0, 
-1, 47.1877, 0, -1, 0.328957,-99) , 
2, 106.252, 0, 0, 0.401652,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503586,-99) , 
NN(
0, 
0, 
-1, 52.0968, 0, -1, 0.111565,-99) , 
3, 101.232, 0, 0, 0.122813,-99) , 
4, 143.039, 0, 0, 0.280594,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.347184);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394758,-99) , 
5, 29.4674, 0, 0, 0.469619,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.179381,-99) , 
2, 141.237, 0, 0, 0.256793,-99) , 
7, 2.26727, 1, 0, 0.452407,-99) , 
NN(
0, 
0, 
-1, 52.0968, 0, -1, 0.180972,-99) , 
4, 143.039, 0, 0, 0.344033,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.331703);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386192,-99) , 
7, 1.2139, 1, 0, 0.564517,-99) , 
NN(
0, 
0, 
-1, 126.762, 1, -1, 0.408405,-99) , 
6, 2.84206, 0, 0, 0.435327,-99) , 
NN(
0, 
0, 
-1, 52.0968, 0, -1, 0.238197,-99) , 
4, 143.039, 0, 0, 0.360985,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.165768);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.117627,-99) , 
7, 3.08307, 1, 0, 0.502157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497361,-99) , 
NN(
0, 
0, 
-1, 52.0968, 0, -1, 0.303457,-99) , 
4, 143.039, 0, 0, 0.426818,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.213928);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264078,-99) , 
0, 166.504, 1, 0, 0.488658,-99) , 
NN(
0, 
0, 
-1, 49.4475, 0, -1, 0.384847,-99) , 
0, 57.9763, 0, 0, 0.450101,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 2.42367, 1, 0, 0.573912,-99) , 
NN(
0, 
0, 
-1, 25.4419, 0, -1, 0.134064,-99) , 
0, 99.9568, 0, 0, 0.233349,-99) , 
3, 34.2047, 0, 0, 0.415585,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.212313);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387331,-99) , 
6, 1.19792, 0, 0, 0.492437,-99) , 
NN(
0, 
0, 
-1, 3.4008, 1, -1, 0.405962,-99) , 
7, 0.680313, 1, 0, 0.441844,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.76142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289022,-99) , 
6, 2.3905, 0, 0, 0.638858,-99) , 
NN(
0, 
0, 
-1, 131.53, 0, -1, 0.179597,-99) , 
4, 222.278, 0, 0, 0.247929,-99) , 
3, 34.2047, 0, 0, 0.412463,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.15837);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504856,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435279,-99) , 
1, 53.5494, 0, 0, 0.461281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.457783,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 2.42367, 1, 0, 0.542421,-99) , 
NN(
0, 
0, 
-1, 25.4419, 0, -1, 0.191373,-99) , 
0, 99.9568, 0, 0, 0.274376,-99) , 
3, 34.2047, 0, 0, 0.431227,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.127813);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.40071, 1, -1, 0.467753,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.696388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363733,-99) , 
6, 2.3905, 0, 0, 0.606751,-99) , 
NN(
0, 
0, 
-1, 131.53, 0, -1, 0.231121,-99) , 
4, 222.278, 0, 0, 0.288163,-99) , 
3, 34.2047, 0, 0, 0.442553,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0904353);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355063,-99) , 
3, 196.978, 1, 0, 0.502987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.499661,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393795,-99) , 
6, 2.3905, 0, 0, 0.594204,-99) , 
NN(
0, 
0, 
-1, 131.53, 0, -1, 0.254609,-99) , 
4, 222.278, 0, 0, 0.306691,-99) , 
3, 34.2047, 0, 0, 0.473253,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.102238);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472635,-99) , 
2, 58.7706, 1, 0, 0.481839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.478793,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.320485,-99) , 
3, 34.2047, 0, 0, 0.457493,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0745814);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406939,-99) , 
4, 113.51, 0, 0, 0.499349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.496344,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.343146,-99) , 
3, 34.2047, 0, 0, 0.476004,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0695368);
  fForest.push_back( 
NN(
0, 
0, 
-1, 34.2047, 0, -1, 0.465288,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0607172);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440153,-99) , 
0, 133.927, 1, 0, 0.501405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.498593,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.376322,-99) , 
3, 34.2047, 0, 0, 0.482623,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.11968);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433109,-99) , 
1, 42.8413, 1, 0, 0.530748,-99) , 
NN(
0, 
0, 
-1, 20.8886, 0, -1, 0.455972,-99) , 
0, 95.9514, 0, 0, 0.476753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.474179,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0475414);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.449491, 1, 1, 0.510801,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.40727,-99) , 
3, 34.2047, 0, 0, 0.497528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.494984,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0756455);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436077,-99) , 
4, 234.419, 1, 0, 0.50593,-99) , 
NN(
0, 
0, 
-1, 23.4226, 0, -1, 0.44591,-99) , 
1, 21.4251, 0, 0, 0.488681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.486238,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0482239);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489066,-99) , 
6, 0.449491, 1, 0, 0.493914,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.425705,-99) , 
3, 34.2047, 0, 0, 0.485234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.482893,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.062656);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483342,-99) , 
1, 21.4251, 1, 0, 0.532894,-99) , 
NN(
0, 
0, 
-1, 1.74126, 1, -1, 0.481328,-99) , 
0, 95.9514, 0, 0, 0.495694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.493358,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0580907);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467005,-99) , 
4, 113.51, 0, 0, 0.517429,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.448251,-99) , 
3, 34.2047, 0, 0, 0.508691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.506364,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0772603);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404832,-99) , 
6, 2.09791, 0, 0, 0.528345,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260229,-99) , 
7, 1.74126, 1, 0, 0.48918,-99) , 
0, 95.9514, 0, 0, 0.500078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.497853,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0703121);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478515,-99) , 
1, 21.4251, 1, 0, 0.517859,-99) , 
NN(
0, 
0, 
-1, 22.1995, 0, -1, 0.472554,-99) , 
0, 95.9514, 0, 0, 0.485126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.483045,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0611566);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481976,-99) , 
7, 0.808134, 0, 0, 0.511442,-99) , 
NN(
0, 
0, 
-1, 23.4226, 0, -1, 0.470203,-99) , 
1, 21.4251, 0, 0, 0.49974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.497667,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0462909);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492619,-99) , 
0, 92.0351, 0, 0, 0.507193,-99) , 
NN(
0, 
0, 
-1, 135.117, 0, -1, 0.321697,-99) , 
7, 2.86245, 1, 0, 0.503273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501228,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0455766);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497146,-99) , 
5, 40.9009, 0, 0, 0.513453,-99) , 
NN(
0, 
0, 
-1, 62.7675, 0, -1, 0.37254,-99) , 
7, 2.64228, 1, 0, 0.508464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.506443,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0532331);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461729,-99) , 
0, 34.4079, 0, 0, 0.514979,-99) , 
NN(
0, 
0, 
-1, 135.117, 0, -1, 0.342062,-99) , 
7, 2.86245, 1, 0, 0.511377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.509389,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0141041);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49898,-99) , 
0, 236.103, 0, 0, 0.502086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499088,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0473385);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456269,-99) , 
7, 1.67754, 1, 0, 0.505486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.504386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.502488,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0222693);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.669296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494662,-99) , 
0, 236.103, 0, 0, 0.497797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.496739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.494912,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.012028);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 236.103, 0, 1, 0.503165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.502107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.50028,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.016868);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497222,-99) , 
0, 236.103, 0, 0, 0.500158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497308,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0140551);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 236.103, 0, 1, 0.504225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.50318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501375,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0151355);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497925,-99) , 
0, 236.103, 0, 0, 0.500711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.49968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497901,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0657982);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 21.8526, 0, 0, 0.515735,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434801,-99) , 
6, 2.09283, 1, 0, 0.477562,-99) , 
2, 105.6, 1, 0, 0.50333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.501551,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0308114);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489874,-99) , 
0, 236.103, 0, 0, 0.492861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.491885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.490181,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0154057);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497576,-99) , 
0, 236.103, 0, 0, 0.500288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497608,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.013281);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 221.696, 0, 1, 0.504003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.503027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501323,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0151707);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497808,-99) , 
0, 221.696, 0, 0, 0.500683,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.49972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498038,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.013817);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 236.103, 0, 1, 0.504309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.503347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501665,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0131127);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498413,-99) , 
0, 236.103, 0, 0, 0.500855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498247,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0131679);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 236.103, 0, 1, 0.504018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.503068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.50141,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0504664);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487779,-99) , 
5, 29.4674, 1, 0, 0.505329,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.460476,-99) , 
3, 34.2047, 0, 0, 0.499791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.498152,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0646503);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481201,-99) , 
0, 48.8485, 1, 0, 0.527121,-99) , 
NN(
0, 
0, 
-1, 23.4226, 0, -1, 0.482509,-99) , 
5, 40.9009, 0, 0, 0.499728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498089,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0299043);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 221.696, 0, 1, 0.512537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.51163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.510003,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0149521);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 221.696, 0, 1, 0.505064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.504182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.502602,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0128805);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498612,-99) , 
0, 221.696, 0, 0, 0.501326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498901,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0331406);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493032,-99) , 
0, 92.0351, 0, 0, 0.504405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.503537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.50198,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0286217);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386982,-99) , 
7, 2.85167, 1, 0, 0.507804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.506945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.505403,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0361411);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487888,-99) , 
5, 40.9009, 0, 0, 0.500915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498579,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0552788);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477814,-99) , 
6, 2.57161, 1, 0, 0.507838,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 62.3009, 0, 0, 0.457114,-99) , 
6, 0.748579, 0, 0, 0.502167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.500684,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0246889);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44538,-99) , 
6, 0.748579, 0, 0, 0.49791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.497114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.495668,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0266527);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490823,-99) , 
0, 236.103, 0, 0, 0.493118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.49234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.490925,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0329788);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494521,-99) , 
1, 9.64226, 1, 0, 0.502477,-99) , 
NN(
0, 
0, 
-1, 62.7675, 0, -1, 0.392536,-99) , 
7, 2.64228, 1, 0, 0.498768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497353,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0153352);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 221.696, 0, 1, 0.505531,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.504756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.503347,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0445342);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.182454,-99) , 
3, 6.53545, 0, 0, 0.507596,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309047,-99) , 
2, 130.947, 0, 0, 0.462379,-99) , 
3, 136.74, 1, 0, 0.500935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.499547,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0479764);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479486,-99) , 
0, 77.6283, 0, 0, 0.494383,-99) , 
NN(
0, 
0, 
-1, 62.7675, 0, -1, 0.388319,-99) , 
7, 2.64228, 1, 0, 0.490809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.489428,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0247702);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454837,-99) , 
7, 1.67754, 1, 0, 0.494538,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.493819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.492461,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0304342);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488455,-99) , 
0, 236.103, 0, 0, 0.490508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.489803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.488473,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0106485);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423399,-99) , 
5, 102.25, 1, 0, 0.497847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.497142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.495812,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0190728);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465162,-99) , 
7, 1.67754, 1, 0, 0.495374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.494677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.493359,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0269161);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490177,-99) , 
0, 221.696, 0, 0, 0.492269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.491582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.490286,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0115222);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428396,-99) , 
5, 102.25, 1, 0, 0.498704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.496721,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.024387);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492367,-99) , 
6, 0.449501, 1, 0, 0.496028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.495349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.494067,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0156159);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435265,-99) , 
5, 102.25, 1, 0, 0.501295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499337,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0158513);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462625,-99) , 
6, 0.748579, 0, 0, 0.497667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.496999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.495738,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0256883);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491217,-99) , 
6, 0.449501, 1, 0, 0.494589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.49393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.492686,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0195651);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465084,-99) , 
6, 0.748579, 0, 0, 0.500137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498237,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0110664);
  fForest.push_back( 
NN(
0, 
0, 
-1, 323.802, 1, -1, 0.494467,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.00850964);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408524,-99) , 
7, 2.85167, 1, 0, 0.499101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497233,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0158255);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495408,-99) , 
0, 236.103, 0, 0, 0.49705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.496409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.495198,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0117003);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412112,-99) , 
7, 2.85167, 1, 0, 0.500867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499016,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0187141);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494904,-99) , 
6, 0.449501, 1, 0, 0.498047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.497413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.496217,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.00780506);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 221.696, 0, 1, 0.502089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500261,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0100925);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498412,-99) , 
0, 221.696, 0, 0, 0.500138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.49951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498324,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0145299);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418043,-99) , 
7, 2.85167, 1, 0, 0.502551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500738,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0149747);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462404,-99) , 
0, 34.4079, 0, 0, 0.499049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.49843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.49726,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0115917);
  fForest.push_back( 
NN(
0, 
0, 
-1, 323.802, 1, -1, 0.494204,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.00967908);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440197,-99) , 
5, 102.25, 1, 0, 0.498866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497102,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0159121);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472413,-99) , 
7, 1.67754, 1, 0, 0.496617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.496012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.494869,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0209802);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492493,-99) , 
0, 236.103, 0, 0, 0.494023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.493426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.492298,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.00628715);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401428,-99) , 
3, 240.142, 1, 0, 0.499083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497359,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0349767);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494639,-99) , 
2, 58.7706, 1, 0, 0.502795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.454619,-99) , 
3, 34.2047, 0, 0, 0.496957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.495835,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.045298);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458088,-99) , 
0, 133.927, 1, 0, 0.508793,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.447443,-99) , 
3, 34.2047, 0, 0, 0.501367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.500254,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0360961);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467011,-99) , 
3, 131.878, 1, 0, 0.49977,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.458667,-99) , 
3, 34.2047, 0, 0, 0.494801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.493726,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.030912);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487599,-99) , 
0, 221.696, 0, 0, 0.48958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.489029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.48796,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.028524);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487216,-99) , 
5, 40.9009, 0, 0, 0.49697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.496418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.49535,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.017488);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495461,-99) , 
2, 32.7084, 1, 0, 0.498596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.49805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.496994,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0223901);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494918,-99) , 
0, 92.0351, 0, 0, 0.502473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500872,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0126425);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 9.63843, 1, 1, 0.50476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.504218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.50317,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0167273);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496966,-99) , 
1, 9.63843, 1, 0, 0.5016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500029,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0123023);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.449501, 1, 1, 0.504612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.504078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.503045,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0119166);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498448,-99) , 
6, 0.449501, 1, 0, 0.501537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499988,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0112605);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 32.7084, 1, 1, 0.504108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.503581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.502561,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0438185);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490481,-99) , 
5, 29.4674, 1, 0, 0.506065,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.46202,-99) , 
3, 34.2047, 0, 0, 0.500775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.499763,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0312124);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489487,-99) , 
5, 40.9009, 0, 0, 0.501228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500718,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499708,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0198693);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467056,-99) , 
6, 2.99167, 1, 0, 0.503001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.502497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501498,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0111642);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497313,-99) , 
0, 221.696, 0, 0, 0.498857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497381,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0113495);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423827,-99) , 
7, 2.85167, 1, 0, 0.501527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500051,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0178213);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478295,-99) , 
7, 0.335678, 0, 0, 0.49879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.4983,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.49733,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0270298);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48824,-99) , 
7, 0.50341, 1, 0, 0.496115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.495633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.494676,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0191048);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475998,-99) , 
7, 0.335678, 0, 0, 0.498541,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497114,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.0375907);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473053,-99) , 
5, 58.9334, 1, 0, 0.500971,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.45283,-99) , 
3, 34.2047, 0, 0, 0.495206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.494269,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.0275306);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489466,-99) , 
2, 32.7084, 1, 0, 0.492502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.492042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.491106,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0269689);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487897,-99) , 
2, 93.8278, 0, 0, 0.498605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497211,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.0136877);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496773,-99) , 
2, 32.7084, 1, 0, 0.499389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498011,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.00913337);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499581,-99) , 
6, 0.449501, 1, 0, 0.502424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501047,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0212434);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472445,-99) , 
0, 34.4079, 0, 0, 0.504394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.503941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.503018,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0212618);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493692,-99) , 
6, 1.34674, 1, 0, 0.500026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498675,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.020389);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471618,-99) , 
6, 0.748579, 0, 0, 0.502529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.502087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501186,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.0157572);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495705,-99) , 
6, 0.449501, 1, 0, 0.498572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497253,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0116516);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427527,-99) , 
7, 2.85167, 1, 0, 0.50197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500652,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.0100076);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497675,-99) , 
0, 221.696, 0, 0, 0.49916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497857,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.00974554);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413869,-99) , 
3, 240.142, 1, 0, 0.501553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.50025,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0525336);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 21.8526, 0, 0, 0.507596,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468832,-99) , 
7, 2.0523, 0, 0, 0.480534,-99) , 
2, 105.6, 1, 0, 0.498751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.497884,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0313969);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481609,-99) , 
2, 93.8278, 0, 0, 0.493912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.493502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.492646,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.0128476);
  fForest.push_back( 
NN(
0, 
0, 
-1, 323.802, 1, -1, 0.493577,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0164934);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474239,-99) , 
7, 1.67754, 1, 0, 0.498037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.497633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.496788,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0196694);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492976,-99) , 
2, 32.7084, 1, 0, 0.495349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.49495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.494117,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0216819);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49191,-99) , 
5, 40.9009, 0, 0, 0.499716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498485,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.0224568);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489254,-99) , 
3, 90.0696, 1, 0, 0.500939,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499718,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.00802643);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4986,-99) , 
0, 221.696, 0, 0, 0.500076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.49887,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.00857395);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49941,-99) , 
6, 0.449501, 1, 0, 0.501994,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500789,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.0147038);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433685,-99) , 
7, 2.85167, 1, 0, 0.503843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.503453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.502638,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.00738604);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498867,-99) , 
0, 221.696, 0, 0, 0.500296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499109,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.00647814);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 221.696, 0, 1, 0.502062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500875,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.00677552);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499094,-99) , 
0, 221.696, 0, 0, 0.500442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.50006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499263,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.0166368);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477192,-99) , 
6, 0.748579, 0, 0, 0.502062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.50168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500883,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0388688);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476633,-99) , 
5, 14.7344, 0, 0, 0.503554,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.460619,-99) , 
3, 34.2047, 0, 0, 0.498457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.49767,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0267834);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488969,-99) , 
1, 9.63843, 1, 0, 0.493266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.492901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.492125,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.015944);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495303,-99) , 
6, 0.449501, 1, 0, 0.498098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.497734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.496961,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0097967);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43586,-99) , 
7, 2.85167, 1, 0, 0.501536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500399,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.0184268);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49393,-99) , 
6, 1.34674, 1, 0, 0.499172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498047,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0173745);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472032,-99) , 
6, 0.748579, 0, 0, 0.501344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500224,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0205889);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490514,-99) , 
0, 77.6283, 0, 0, 0.49797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.497617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.496867,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.0385722);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49026,-99) , 
5, 29.4674, 1, 0, 0.504198,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.456649,-99) , 
3, 34.2047, 0, 0, 0.498571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.497825,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.0274797);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488741,-99) , 
5, 40.9009, 0, 0, 0.498888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.498544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497798,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0109115);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497874,-99) , 
6, 0.449501, 1, 0, 0.500428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.49935,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.0200657);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482184,-99) , 
7, 1.67754, 1, 0, 0.502781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.502441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501703,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.0189052);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486663,-99) , 
3, 60.0551, 0, 0, 0.49951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498449,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.00622197);
  fForest.push_back( 
NN(
0, 
0, 
-1, 323.802, 1, -1, 0.496889,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.00497546);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41763,-99) , 
3, 240.142, 1, 0, 0.499492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498445,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.0055296);
  fForest.push_back( 
NN(
0, 
0, 
-1, 323.802, 1, -1, 0.497235,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.00517576);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420187,-99) , 
3, 240.142, 1, 0, 0.49966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498618,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.009267);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470596,-99) , 
0, 34.4079, 0, 0, 0.498396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.49807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.49736,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.0137514);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495214,-99) , 
0, 221.696, 0, 0, 0.49649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.496166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.495461,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.0110262);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469136,-99) , 
0, 149.662, 1, 0, 0.499777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498749,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.0280024);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496128,-99) , 
2, 58.7706, 1, 0, 0.502497,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.456882,-99) , 
3, 34.2047, 0, 0, 0.497121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.496424,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.0211886);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483635,-99) , 
2, 63.2681, 0, 0, 0.501002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.500684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499991,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.0369525);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481043,-99) , 
1, 64.2576, 1, 0, 0.503989,-99) , 
NN(
0, 
0, 
-1, 29.2867, 1, -1, 0.454614,-99) , 
3, 34.2047, 0, 0, 0.498179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.497493,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.0163876);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.828346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 22.5855, 1, 0, 0.662903,-99) , 
NN(
0, 
0, 
-1, 2.83069, 1, -1, 0.49452,-99) , 
7, 3.30279, 0, 0, 0.49548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.4948,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.0115007);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497395,-99) , 
2, 32.7084, 1, 0, 0.499848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.499539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498859,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.0161482);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496807,-99) , 
6, 1.34674, 1, 0, 0.502406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.502098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501418,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.0105522);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 221.696, 0, 1, 0.504309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.504002,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.503325,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.0052761);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 221.696, 0, 1, 0.501671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500697,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.0298907);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444157,-99) , 
0, 171.902, 1, 0, 0.504372,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.467574,-99) , 
3, 34.2047, 0, 0, 0.50005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.499384,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.0204625);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.824659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 22.5855, 1, 0, 0.658971,-99) , 
NN(
0, 
0, 
-1, 2.83069, 1, -1, 0.492371,-99) , 
7, 3.30279, 0, 0, 0.493296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.492647,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.0337033);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492476,-99) , 
7, 0.64655, 1, 0, 0.502617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.46639,-99) , 
3, 34.2047, 0, 0, 0.49837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.497717,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.0120523);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.825874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 22.5855, 1, 0, 0.663967,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295362,-99) , 
7, 2.83069, 1, 0, 0.497993,-99) , 
7, 3.30279, 0, 0, 0.498914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.49827,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.027828);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495381,-99) , 
7, 1.93922, 0, 0, 0.501244,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.456383,-99) , 
3, 34.2047, 0, 0, 0.495988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.49535,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.0218142);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479017,-99) , 
7, 0.335678, 0, 0, 0.501612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.52296, 1, 0, 0.501324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.500681,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.0163762);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498123,-99) , 
7, 2.38912, 0, 0, 0.500226,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.430226,-99) , 
7, 2.64228, 1, 0, 0.498054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.497422,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.0359287);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485736,-99) , 
5, 14.7344, 0, 0, 0.506755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.463765,-99) , 
3, 34.2047, 0, 0, 0.501724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.501087,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.0304801);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49196,-99) , 
5, 10.2262, 1, 0, 0.49897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.421363,-99) , 
7, 2.64228, 1, 0, 0.496573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.495949,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.0306227);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496337,-99) , 
5, 29.4674, 1, 0, 0.506592,-99) , 
NN(
0, 
0, 
-1, 29.2867, 1, -1, 0.454612,-99) , 
3, 34.2047, 0, 0, 0.500529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.499902,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.0333833);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483914,-99) , 
2, 63.2681, 0, 0, 0.504854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.416762,-99) , 
7, 2.64228, 1, 0, 0.502147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.501525,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.0223994);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496822,-99) , 
7, 1.93913, 0, 0, 0.501494,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.157163,-99) , 
3, 49.3959, 0, 0, 0.449825,-99) , 
7, 2.26239, 1, 0, 0.498099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.497482,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.0273147);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401022,-99) , 
6, 0.150423, 0, 0, 0.506349,-99) , 
NN(
0, 
0, 
-1, 49.3959, 0, -1, 0.445885,-99) , 
7, 2.26239, 1, 0, 0.50238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.501764,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.0301875);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486059,-99) , 
6, 2.24397, 1, 0, 0.499307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.413836,-99) , 
7, 2.64228, 1, 0, 0.496697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.496093,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.023377);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495027,-99) , 
7, 1.93913, 0, 0, 0.499042,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500153,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167135,-99) , 
3, 49.3959, 0, 0, 0.449683,-99) , 
7, 2.26239, 1, 0, 0.495809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.495207,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.0508315);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454889,-99) , 
0, 41.561, 0, 0, 0.503843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327003,-99) , 
0, 247.852, 1, 0, 0.502469,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.741616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345935,-99) , 
3, 75.4784, 1, 0, 0.485552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.390904,-99) , 
7, 2.72061, 1, 0, 0.499675,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.0167898);
  fForest.push_back( 
NN(
0, 
0, 
-1, 3.40071, 1, -1, 0.491606,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.0151596);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408492,-99) , 
6, 0.150423, 0, 0, 0.500045,-99) , 
NN(
0, 
0, 
-1, 49.3959, 0, -1, 0.443856,-99) , 
7, 2.26239, 1, 0, 0.496383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.495803,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.0250609);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492718,-99) , 
2, 32.7084, 1, 0, 0.495691,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.413681,-99) , 
7, 2.64228, 1, 0, 0.493224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.492651,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.017357);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418025,-99) , 
6, 0.150423, 0, 0, 0.501964,-99) , 
NN(
0, 
0, 
-1, 49.3959, 0, -1, 0.448991,-99) , 
7, 2.26239, 1, 0, 0.498518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.497937,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.0305599);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493176,-99) , 
2, 58.7706, 1, 0, 0.499022,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.463509,-99) , 
3, 34.2047, 0, 0, 0.494898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.494327,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.0340564);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481051,-99) , 
5, 14.7344, 0, 0, 0.504295,-99) , 
NN(
0, 
0, 
-1, 24.1302, 0, -1, 0.457075,-99) , 
3, 34.2047, 0, 0, 0.498818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.49825,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.0248324);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493502,-99) , 
1, 9.64226, 1, 0, 0.498305,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.412217,-99) , 
7, 2.64228, 1, 0, 0.495739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.495179,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.0134251);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.93913, 0, 1, 0.503159,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.178993,-99) , 
3, 49.3959, 0, 0, 0.453858,-99) , 
7, 2.26239, 1, 0, 0.499962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.4994,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.0152331);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49747,-99) , 
7, 2.38912, 0, 0, 0.499466,-99) , 
NN(
0, 
0, 
-1, 62.7675, 0, -1, 0.405514,-99) , 
7, 2.64228, 1, 0, 0.496672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.496116,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.0153933);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533537,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499139,-99) , 
3, 150.098, 0, 0, 0.503061,-99) , 
NN(
0, 
0, 
-1, 62.7675, 0, -1, 0.409191,-99) , 
7, 2.64228, 1, 0, 0.500273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499718,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.0179588);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.38912, 0, 1, 0.506032,-99) , 
NN(
0, 
0, 
-1, 62.7675, 0, -1, 0.412918,-99) , 
7, 2.64228, 1, 0, 0.50327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.502715,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.0102594);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499756,-99) , 
7, 2.38912, 0, 0, 0.501543,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.417278,-99) , 
7, 2.64228, 1, 0, 0.499047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.498502,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.0158627);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.93913, 0, 1, 0.504653,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183982,-99) , 
3, 49.3959, 0, 0, 0.453477,-99) , 
7, 2.26239, 1, 0, 0.501348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.500802,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.0124522);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498384,-99) , 
7, 2.38912, 0, 0, 0.500052,-99) , 
NN(
0, 
0, 
-1, 62.7675, 0, -1, 0.412544,-99) , 
7, 2.64228, 1, 0, 0.497464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.49692,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.0168966);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498429,-99) , 
6, 2.84213, 0, 0, 0.502991,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.415565,-99) , 
7, 2.64228, 1, 0, 0.500409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.499865,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.0301035);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494328,-99) , 
6, 2.09443, 1, 0, 0.506456,-99) , 
NN(
0, 
0, 
-1, 49.3959, 0, -1, 0.45167,-99) , 
7, 2.26239, 1, 0, 0.502927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.502384,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.0310516);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483923,-99) , 
6, 1.1972, 0, 0, 0.506032,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 62.7675, 0, 0, 0.419963,-99) , 
7, 2.64228, 1, 0, 0.503498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.502962,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.0198319);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49949,-99) , 
6, 0.449491, 1, 0, 0.503196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.466994,-99) , 
3, 34.2047, 0, 0, 0.499012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.498479,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.0292855);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497683,-99) , 
7, 0.64655, 1, 0, 0.5074,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.462818,-99) , 
3, 34.2047, 0, 0, 0.502251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.501721,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.0647202);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485105,-99) , 
2, 84.2992, 0, 0, 0.508743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 323.802, 1, 0, 0.508197,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.497112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.456177,-99) , 
3, 34.2047, 0, 0, 0.502196,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.0846052);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389616,-99) , 
2, 52.4099, 0, 0, 0.548248,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417563,-99) , 
4, 129.754, 0, 0, 0.496766,-99) , 
2, 58.7706, 1, 0, 0.504756,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.483699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.444857,-99) , 
3, 34.2047, 0, 0, 0.497885,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.10409);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384455,-99) , 
2, 50.8207, 0, 0, 0.546935,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465822,-99) , 
6, 2.69253, 0, 0, 0.479807,-99) , 
2, 58.7706, 1, 0, 0.490124,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.465986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.429831,-99) , 
3, 34.2047, 0, 0, 0.483244,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.0806543);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 97.2504, 0, 0, 0.515354,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462068,-99) , 
1, 10.9877, 1, 0, 0.47405,-99) , 
4, 189.379, 1, 0, 0.500805,-99) , 
NN(
0, 
0, 
-1, 29.2867, 1, -1, 0.411055,-99) , 
3, 34.2047, 0, 0, 0.490597,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.0316202);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.40071, 1, -1, 0.49849,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286803,-99) , 
2, 96.2997, 1, 0, 0.428876,-99) , 
6, 2.9916, 1, 0, 0.493849,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 24.1302, 0, 0, 0.46399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 29.2867, 1, 0, 0.430711,-99) , 
3, 34.2047, 0, 0, 0.486696,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.0409721);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 3.40071, 1, 0, 0.506395,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293314,-99) , 
2, 96.2997, 1, 0, 0.427314,-99) , 
6, 2.9916, 1, 0, 0.501139,-99) , 
NN(
0, 
0, 
-1, 29.2867, 1, -1, 0.424881,-99) , 
3, 34.2047, 0, 0, 0.492515,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.106812);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 22.1995, 0, 0, 0.514557,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.233977,-99) , 
3, 69.9647, 1, 0, 0.325408,-99) , 
0, 115.431, 1, 0, 0.497501,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.266589,-99) , 
2, 50.5487, 0, 0, 0.513247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.174283,-99) , 
1, 11.1145, 1, 0, 0.337475,-99) , 
0, 71.6013, 0, 0, 0.458914,-99) , 
6, 2.54305, 1, 0, 0.485097,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.0837632);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 459.994, 1, -1, 0.469328,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330217,-99) , 
2, 89.4721, 1, 0, 0.465564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 51.6095, 0, 0, 0.409782,-99) , 
6, 2.99167, 1, 0, 0.464349,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.0418816);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 459.994, 1, -1, 0.490232,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348999,-99) , 
2, 89.4721, 1, 0, 0.463033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 51.6095, 0, 0, 0.409138,-99) , 
6, 2.99167, 1, 0, 0.48352,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.0377084);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 20.8091, 0, 0, 0.50217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319571,-99) , 
4, 459.994, 1, 0, 0.500701,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358574,-99) , 
2, 89.4721, 1, 0, 0.461751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 51.6095, 0, 0, 0.40881,-99) , 
6, 2.99167, 1, 0, 0.493135,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_mm_eq1j::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_mm_eq1j::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
