// Class: ReadBDT_ee_eq1j
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_ee_eq1j
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.30/05       [335365]
Creator        : gerbaudo
Date           : Tue Jan 14 18:18:47 2014
Host           : Linux lxbuild147.cern.ch 2.6.18-194.26.1.el5 #1 SMP Wed Nov 10 09:51:11 CET 2010 i686 i686 i386 GNU/Linux
Dir            : /data7/atlas/gerbaudo/wh/Susy2013_Nt_01_04_dev/SusyTest0/run
Training events: 316363
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "50" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "316363" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
mll                           mll                           mll                           mll                                                             'F'    [19.6087360382,1293.55187988]
mtmin                         mtmin                         mtmin                         mtmin                                                           'F'    [0.000115169568744,678.743347168]
mtmax                         mtmax                         mtmax                         mtmax                                                           'F'    [0.864526808262,1237.29394531]
mtllmet                       mtllmet                       mtllmet                       mtllmet                                                         'F'    [0.000212505285162,1295.83288574]
ht                            ht                            ht                            ht                                                              'F'    [74.3087005615,2013.91003418]
metrel                        metrel                        metrel                        metrel                                                          'F'    [4.74300468341e-05,668.489746094]
dphill                        dphill                        dphill                        dphill                                                          'F'    [8.51154327393e-05,3.14159154892]
detall                        detall                        detall                        detall                                                          'F'    [2.92062759399e-06,4.82775783539]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_ee_eq1jNode
   
#ifndef BDT_ee_eq1jNode__def
#define BDT_ee_eq1jNode__def
   
class BDT_ee_eq1jNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_ee_eq1jNode ( BDT_ee_eq1jNode* left,BDT_ee_eq1jNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_ee_eq1jNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_ee_eq1jNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_ee_eq1jNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_ee_eq1jNode*   fLeft;     // pointer to the left daughter node
   BDT_ee_eq1jNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_ee_eq1jNode::~BDT_ee_eq1jNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_ee_eq1jNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_ee_eq1jNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_ee_eq1j : public IClassifierReader {

 public:

   // constructor
   ReadBDT_ee_eq1j( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_ee_eq1j" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mll", "mtmin", "mtmax", "mtllmet", "ht", "metrel", "dphill", "detall" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 19.608736038208;
      fVmax[0] = 1293.55187988281;
      fVmin[1] = 0.000115169568744022;
      fVmax[1] = 678.743347167969;
      fVmin[2] = 0.864526808261871;
      fVmax[2] = 1237.2939453125;
      fVmin[3] = 0.000212505285162479;
      fVmax[3] = 1295.83288574219;
      fVmin[4] = 74.3087005615234;
      fVmax[4] = 2013.91003417969;
      fVmin[5] = 4.74300468340516e-05;
      fVmax[5] = 668.48974609375;
      fVmin[6] = 8.51154327392578e-05;
      fVmax[6] = 3.14159154891968;
      fVmin[7] = 2.92062759399414e-06;
      fVmax[7] = 4.82775783538818;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_ee_eq1j() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_ee_eq1jNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_ee_eq1j::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_ee_eq1jNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_ee_eq1jNode*)current->GetRight();
         else current=(BDT_ee_eq1jNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_ee_eq1j::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(3.27810120794401);
  fForest.push_back( 
NN(
0, 
0, 
-1, 118.62, 0, -1, 0.00141926,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.65086);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421984,-99) , 
6, 0.597466, 1, 0, 0.514327,-99) , 
NN(
0, 
0, 
-1, 1.79541, 0, -1, 0.234054,-99) , 
0, 76.4966, 1, 0, 0.271748,-99) , 
NN(
0, 
0, 
-1, 78.4232, 0, -1, 0.0241667,-99) , 
2, 118.62, 0, 0, 0.0363301,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.930561);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 62.1525, 0, 1, 0.581399,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.222847,-99) , 
2, 121.431, 0, 0, 0.291769,-99) , 
5, 31.8343, 0, 0, 0.442015,-99) , 
NN(
0, 
0, 
-1, 166.671, 0, -1, 0.0677804,-99) , 
3, 61.7065, 0, 0, 0.158475,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.739785);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354063,-99) , 
0, 107.324, 0, 0, 0.500757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308974,-99) , 
0, 53.5847, 1, 0, 0.346199,-99) , 
6, 2.39362, 0, 0, 0.416239,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364504,-99) , 
3, 47.5538, 0, 0, 0.503612,-99) , 
NN(
0, 
0, 
-1, 59.4482, 0, -1, 0.0641903,-99) , 
0, 69.3262, 1, 0, 0.114747,-99) , 
4, 166.671, 0, 0, 0.223309,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.508902);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.685813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452232,-99) , 
0, 85.01, 1, 0, 0.505907,-99) , 
NN(
0, 
0, 
-1, 53.7561, 1, -1, 0.286895,-99) , 
6, 0.897696, 0, 0, 0.482239,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317256,-99) , 
5, 32.4931, 1, 0, 0.499429,-99) , 
NN(
0, 
0, 
-1, 59.4482, 0, -1, 0.125673,-99) , 
0, 69.3262, 1, 0, 0.179955,-99) , 
4, 166.671, 0, 0, 0.30409,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.418826);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 98.9123, 0, 1, 0.593671,-99) , 
NN(
0, 
0, 
-1, 236.375, 1, -1, 0.420587,-99) , 
6, 1.49606, 0, 0, 0.55847,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304351,-99) , 
0, 76.6767, 1, 0, 0.388247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.716602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.130467,-99) , 
0, 119.047, 0, 0, 0.147717,-99) , 
3, 40.7579, 0, 0, 0.232657,-99) , 
4, 166.671, 0, 0, 0.377067,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.337605);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.130798,-99) , 
0, 268.398, 1, 0, 0.548036,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393167,-99) , 
1, 32.3245, 0, 0, 0.467523,-99) , 
7, 0.919599, 0, 0, 0.497139,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.178233,-99) , 
1, 18.5191, 0, 0, 0.542922,-99) , 
NN(
0, 
0, 
-1, 79.9799, 1, -1, 0.23436,-99) , 
0, 94.1849, 0, 0, 0.278886,-99) , 
4, 166.671, 0, 0, 0.380284,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.28651);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 231.768, 0, 1, 0.552047,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.138231,-99) , 
6, 0.746797, 0, 0, 0.353799,-99) , 
2, 117.691, 1, 0, 0.528895,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414156,-99) , 
5, 63.6674, 0, 0, 0.432713,-99) , 
NN(
0, 
0, 
-1, 145.513, 0, -1, 0.233116,-99) , 
4, 167.494, 0, 0, 0.33606,-99) , 
0, 80.2727, 1, 0, 0.38853,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.296034);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375053,-99) , 
6, 2.39365, 0, 0, 0.54071,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398775,-99) , 
5, 31.8343, 1, 0, 0.443192,-99) , 
3, 61.7065, 1, 0, 0.476937,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338942,-99) , 
4, 147.42, 0, 0, 0.453696,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.184126,-99) , 
0, 69.3295, 1, 0, 0.238942,-99) , 
3, 33.965, 0, 0, 0.344829,-99) , 
4, 166.671, 0, 0, 0.409613,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.205625);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426994,-99) , 
5, 15.1535, 0, 0, 0.4801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.165, 1, 0, 0.47773,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 9.25994, 0, 0, 0.600812,-99) , 
NN(
0, 
0, 
-1, 87.0824, 1, -1, 0.319382,-99) , 
0, 94.1849, 0, 0, 0.365121,-99) , 
4, 166.671, 0, 0, 0.421342,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.223245);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 77.3837, 1, 0, 0.589081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423251,-99) , 
0, 74.4947, 0, 0, 0.456188,-99) , 
1, 20.8398, 1, 0, 0.501872,-99) , 
NN(
NN(
0, 
0, 
-1, 1.19691, 0, -1, 0.452249,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.217727,-99) , 
5, 19.8072, 0, 0, 0.326967,-99) , 
4, 167.494, 0, 0, 0.396681,-99) , 
0, 80.2727, 1, 0, 0.426847,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.244229);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.743363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499187,-99) , 
6, 2.43637, 1, 0, 0.626062,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412806,-99) , 
0, 93.0359, 0, 0, 0.460166,-99) , 
0, 110.315, 0, 0, 0.488547,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.10699,-99) , 
7, 2.09956, 1, 0, 0.512364,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.212153,-99) , 
4, 149.27, 0, 0, 0.289725,-99) , 
4, 166.862, 0, 0, 0.372089,-99) , 
6, 2.8424, 1, 0, 0.454074,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.211244);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306965,-99) , 
0, 233.419, 1, 0, 0.627614,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424439,-99) , 
0, 84.3975, 1, 0, 0.496991,-99) , 
0, 110.315, 0, 0, 0.519216,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0952434,-99) , 
7, 2.06748, 1, 0, 0.491198,-99) , 
NN(
0, 
0, 
-1, 86.4791, 1, -1, 0.323754,-99) , 
0, 109.041, 0, 0, 0.36549,-99) , 
6, 2.8424, 1, 0, 0.474114,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.16388);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 25.1294, 1, 1, 0.585977,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.719622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472788,-99) , 
0, 97.3552, 0, 0, 0.497912,-99) , 
0, 110.315, 0, 0, 0.512673,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.66051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397821,-99) , 
1, 30.0512, 1, 0, 0.473068,-99) , 
NN(
0, 
0, 
-1, 166.862, 0, -1, 0.328409,-99) , 
5, 21.1868, 0, 0, 0.390191,-99) , 
6, 2.8424, 1, 0, 0.477034,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.142459);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.31364, 0, 1, 0.543556,-99) , 
NN(
0, 
0, 
-1, 97.3071, 0, -1, 0.384191,-99) , 
7, 1.83915, 1, 0, 0.533211,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32412,-99) , 
7, 0.869528, 1, 0, 0.490339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526828,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289922,-99) , 
4, 166.862, 0, 0, 0.365514,-99) , 
5, 21.1868, 0, 0, 0.419095,-99) , 
6, 2.8424, 1, 0, 0.50038,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.117464);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 42.7187, 1, 1, 0.559401,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.225469,-99) , 
6, 0.746797, 0, 0, 0.393609,-99) , 
2, 117.691, 1, 0, 0.54037,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415351,-99) , 
4, 148.38, 0, 0, 0.486678,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340419,-99) , 
0, 138.049, 0, 0, 0.380757,-99) , 
6, 2.84241, 1, 0, 0.451511,-99) , 
0, 80.2727, 1, 0, 0.478411,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.13176);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 42.7187, 1, 1, 0.530279,-99) , 
NN(
0, 
0, 
-1, 51.3906, 0, -1, 0.385665,-99) , 
2, 117.691, 1, 0, 0.513763,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402243,-99) , 
7, 1.67494, 1, 0, 0.496653,-99) , 
NN(
0, 
0, 
-1, 185.302, 0, -1, 0.417616,-99) , 
7, 1.14947, 0, 0, 0.444822,-99) , 
0, 80.2727, 1, 0, 0.465677,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.174709);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441797,-99) , 
0, 95.1827, 0, 0, 0.488023,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 75.3778, 0, 0, 0.198499,-99) , 
0, 246.374, 1, 0, 0.485406,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440825,-99) , 
1, 30.0512, 1, 0, 0.498028,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328007,-99) , 
3, 50.0825, 0, 0, 0.381164,-99) , 
5, 21.1868, 0, 0, 0.432382,-99) , 
6, 2.8424, 1, 0, 0.470465,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.110439);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424865,-99) , 
5, 7.57677, 0, 0, 0.517448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.165, 1, 0, 0.515643,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297659,-99) , 
1, 53.5008, 1, 0, 0.512023,-99) , 
NN(
0, 
0, 
-1, 2.84851, 0, -1, 0.431658,-99) , 
6, 2.79966, 1, 0, 0.462292,-99) , 
6, 2.54321, 1, 0, 0.489679,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0863632);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485653,-99) , 
1, 23.7716, 1, 0, 0.502582,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348951,-99) , 
7, 0.228322, 1, 0, 0.404256,-99) , 
5, 6.06305, 0, 0, 0.486609,-99) , 
NN(
0, 
0, 
-1, 66.2013, 1, -1, 0.207133,-99) , 
5, 127.331, 1, 0, 0.484703,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.112906);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492114,-99) , 
5, 28.5828, 1, 0, 0.530976,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411963,-99) , 
0, 80.2727, 1, 0, 0.452583,-99) , 
5, 18.189, 0, 0, 0.496832,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502279,-99) , 
NN(
0, 
0, 
-1, 1.14874, 0, -1, 0.123416,-99) , 
0, 66.2013, 1, 0, 0.221675,-99) , 
5, 127.331, 1, 0, 0.494996,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.11833);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486834,-99) , 
7, 0.919577, 1, 0, 0.539027,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428675,-99) , 
2, 81.9875, 0, 0, 0.462457,-99) , 
5, 18.189, 0, 0, 0.505744,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 1.03133, 0, 0, 0.378339,-99) , 
NN(
0, 
0, 
-1, 0.446517, 1, -1, 0.0508896,-99) , 
7, 0.716852, 0, 0, 0.226628,-99) , 
5, 127.331, 1, 0, 0.503929,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0832043);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.169206,-99) , 
0, 332.725, 1, 0, 0.520361,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353501,-99) , 
7, 1.14158, 0, 0, 0.439414,-99) , 
5, 6.06305, 0, 0, 0.507436,-99) , 
NN(
0, 
0, 
-1, 132.49, 1, -1, 0.223279,-99) , 
5, 127.331, 1, 0, 0.505635,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0256883);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.843274,-99) , 
NN(
0, 
0, 
-1, 284.712, 1, -1, 0.488256,-99) , 
4, 813.204, 0, 0, 0.489431,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0823493);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396677,-99) , 
0, 176.367, 1, 0, 0.516661,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448829,-99) , 
7, 1.37813, 0, 0, 0.472191,-99) , 
5, 18.189, 0, 0, 0.497382,-99) , 
NN(
0, 
0, 
-1, 132.49, 1, -1, 0.242611,-99) , 
5, 127.331, 1, 0, 0.495809,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.022657);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.84127,-99) , 
NN(
0, 
0, 
-1, 284.712, 1, -1, 0.48975,-99) , 
4, 813.204, 0, 0, 0.490894,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0113285);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.838221,-99) , 
NN(
0, 
0, 
-1, 284.712, 1, -1, 0.495413,-99) , 
4, 813.204, 0, 0, 0.49652,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0208105);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.858522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389546,-99) , 
2, 31.4195, 0, 0, 0.498947,-99) , 
4, 813.204, 0, 0, 0.500076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499334,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.112985);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 94.3652, 0, 1, 0.587511,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.270468,-99) , 
0, 91.6543, 0, 0, 0.402685,-99) , 
3, 19.8114, 0, 0, 0.522271,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.842493,-99) , 
NN(
0, 
0, 
-1, 137.118, 0, -1, 0.478932,-99) , 
4, 830.732, 0, 0, 0.480661,-99) , 
2, 59.7421, 1, 0, 0.494597,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0558263);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.842045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483328,-99) , 
4, 178.968, 0, 0, 0.507643,-99) , 
4, 813.204, 0, 0, 0.508649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.507935,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0457596);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.22608, 0, 1, 0.514718,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372187,-99) , 
3, 134.505, 0, 0, 0.439485,-99) , 
7, 1.83915, 1, 0, 0.510254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.509557,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.00551574);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.828152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.140516,-99) , 
3, 281.533, 1, 0, 0.498927,-99) , 
4, 813.204, 0, 0, 0.499886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499218,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0149511);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.827366,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405004,-99) , 
2, 31.4195, 0, 0, 0.497557,-99) , 
4, 813.204, 0, 0, 0.498516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.497851,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0148623);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.82522,-99) , 
NN(
0, 
0, 
-1, 281.533, 1, -1, 0.494146,-99) , 
4, 813.204, 0, 0, 0.495104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.494449,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.00743117);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.823066,-99) , 
NN(
0, 
0, 
-1, 281.533, 1, -1, 0.497861,-99) , 
4, 813.204, 0, 0, 0.498798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498143,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.00696524);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.821981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.142076,-99) , 
3, 281.533, 1, 0, 0.499719,-99) , 
4, 813.204, 0, 0, 0.500645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.49999,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.00714812);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.82096,-99) , 
NN(
0, 
0, 
-1, 281.533, 1, -1, 0.497988,-99) , 
4, 813.204, 0, 0, 0.498914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498264,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0070054);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.819907,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.143805,-99) , 
3, 281.533, 1, 0, 0.499775,-99) , 
4, 813.204, 0, 0, 0.500691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500041,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.00702664);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.81887,-99) , 
NN(
0, 
0, 
-1, 281.533, 1, -1, 0.498035,-99) , 
4, 813.204, 0, 0, 0.49895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498304,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.00696587);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.817825,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.145542,-99) , 
3, 281.533, 1, 0, 0.499791,-99) , 
4, 813.204, 0, 0, 0.500697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500051,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.00694667);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.816785,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498061,-99) , 
4, 813.204, 0, 0, 0.498966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498325,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.00568187);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.815743,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499797,-99) , 
4, 813.204, 0, 0, 0.500693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500051,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.00628249);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.814888,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498381,-99) , 
4, 813.204, 0, 0, 0.499277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498639,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.00594712);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.813938,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499952,-99) , 
4, 813.204, 0, 0, 0.500838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500201,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0060817);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.813036,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498469,-99) , 
4, 813.204, 0, 0, 0.499356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498722,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.00598064);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.81211,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.49999,-99) , 
4, 813.204, 0, 0, 0.500868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500234,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.00599804);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.811195,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498499,-99) , 
4, 813.204, 0, 0, 0.499377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498747,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.00595619);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.810275,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499999,-99) , 
4, 813.204, 0, 0, 0.500868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500238,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.00594427);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809358,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498514,-99) , 
4, 813.204, 0, 0, 0.499384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498757,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.00591753);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.808439,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.5,-99) , 
4, 813.204, 0, 0, 0.500862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500235,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.00589843);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.807521,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498525,-99) , 
4, 813.204, 0, 0, 0.499387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498764,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.00587569);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.806602,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.5,-99) , 
4, 813.204, 0, 0, 0.500853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.50023,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.00585497);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.805684,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498535,-99) , 
4, 813.204, 0, 0, 0.499388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498769,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.00583342);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.804766,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499999,-99) , 
4, 813.204, 0, 0, 0.500844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500225,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.00581248);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803848,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498545,-99) , 
4, 813.204, 0, 0, 0.49939,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498774,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.00579143);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.80293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499998,-99) , 
4, 813.204, 0, 0, 0.500835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500219,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.00577061);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.802012,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498554,-99) , 
4, 813.204, 0, 0, 0.499391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498779,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.00574986);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.801094,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499997,-99) , 
4, 813.204, 0, 0, 0.500826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500214,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.00572926);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.800176,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498563,-99) , 
4, 813.204, 0, 0, 0.499393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498784,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.00570877);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.799258,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499996,-99) , 
4, 813.204, 0, 0, 0.500817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500208,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0056884);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.798341,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498573,-99) , 
4, 813.204, 0, 0, 0.499394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498789,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0309103);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492305,-99) , 
0, 106.24, 0, 0, 0.501704,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.227201,-99) , 
0, 383.592, 1, 0, 0.500808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500203,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0557665);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.115742, 1, 1, 0.530627,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469206,-99) , 
5, 22.7281, 0, 0, 0.493588,-99) , 
0, 80.2727, 1, 0, 0.50516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.504558,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0696214);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.702767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488828,-99) , 
1, 19.609, 0, 0, 0.526415,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460945,-99) , 
6, 2.39361, 1, 0, 0.490708,-99) , 
1, 21.6732, 1, 0, 0.501975,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 135.868, 0, 0, 0.38825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 132.49, 1, 0, 0.273268,-99) , 
5, 127.331, 1, 0, 0.50066,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.066704);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.883986,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389889,-99) , 
2, 112.85, 1, 0, 0.52572,-99) , 
5, 52.3591, 0, 0, 0.528837,-99) , 
NN(
NN(
0, 
0, 
-1, 16.4957, 0, -1, 0.487401,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.191938,-99) , 
3, 62.0674, 1, 0, 0.301768,-99) , 
4, 379.414, 1, 0, 0.481809,-99) , 
1, 32.3212, 1, 0, 0.503812,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0455257);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496698,-99) , 
7, 1.22608, 0, 0, 0.510472,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385097,-99) , 
3, 134.505, 0, 0, 0.445588,-99) , 
7, 1.83915, 1, 0, 0.506666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.5061,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0342755);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.815484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 281.533, 1, 0, 0.51311,-99) , 
4, 813.204, 0, 0, 0.513934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562534,-99) , 
NN(
0, 
0, 
-1, 1.14874, 0, -1, 0.169529,-99) , 
0, 66.2013, 1, 0, 0.285148,-99) , 
5, 127.331, 1, 0, 0.512666,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0432144);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.797624,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471095,-99) , 
4, 144.082, 0, 0, 0.503942,-99) , 
4, 813.204, 0, 0, 0.504744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.504199,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.00765219);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.803538,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 281.533, 1, 0, 0.499922,-99) , 
4, 813.204, 0, 0, 0.500731,-99) , 
NN(
0, 
0, 
-1, 132.49, 1, -1, 0.280434,-99) , 
5, 127.331, 1, 0, 0.499517,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0491592);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487004,-99) , 
1, 19.8056, 0, 0, 0.522708,-99) , 
NN(
0, 
0, 
-1, 322.929, 1, -1, 0.485569,-99) , 
1, 23.1067, 1, 0, 0.498157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.497633,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0484183);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 16.8621, 0, 0, 0.5165,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.700235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469447,-99) , 
3, 55.0409, 1, 0, 0.478424,-99) , 
2, 112.85, 1, 0, 0.508575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.508052,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0192065);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.801053,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410568,-99) , 
2, 31.4195, 0, 0, 0.500557,-99) , 
4, 813.204, 0, 0, 0.501387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500883,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.01026);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.797974,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.496171,-99) , 
4, 813.204, 0, 0, 0.496999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.496505,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.00513001);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.796315,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498736,-99) , 
4, 813.204, 0, 0, 0.49955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499056,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.00531191);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.795482,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.500018,-99) , 
4, 813.204, 0, 0, 0.500826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500331,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.00519421);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.794616,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498694,-99) , 
4, 813.204, 0, 0, 0.499501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499009,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.00522696);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.793767,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500661,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499992,-99) , 
4, 813.204, 0, 0, 0.500793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500301,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.00518438);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.79291,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498689,-99) , 
4, 813.204, 0, 0, 0.499489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.00517972);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.792058,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499985,-99) , 
4, 813.204, 0, 0, 0.500778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500289,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.00515618);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.791203,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498694,-99) , 
4, 813.204, 0, 0, 0.499487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.00514225);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.79035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499983,-99) , 
4, 813.204, 0, 0, 0.500769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500282,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.00512363);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.789497,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.4987,-99) , 
4, 813.204, 0, 0, 0.499487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499002,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0051075);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.788644,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499981,-99) , 
4, 813.204, 0, 0, 0.500761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500277,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.00509025);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.787791,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498708,-99) , 
4, 813.204, 0, 0, 0.499487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499005,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0050737);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.786939,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.49998,-99) , 
4, 813.204, 0, 0, 0.500753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500271,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00505693);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.786087,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498715,-99) , 
4, 813.204, 0, 0, 0.499488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499008,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0050404);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.785236,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.49998,-99) , 
4, 813.204, 0, 0, 0.500745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500266,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.00502388);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.784385,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.498723,-99) , 
4, 813.204, 0, 0, 0.499489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499011,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00500748);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.783534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 312.815, 1, 0, 0.499979,-99) , 
4, 813.204, 0, 0, 0.500738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500261,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00499115);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.782683,-99) , 
NN(
0, 
0, 
-1, 312.815, 1, -1, 0.49873,-99) , 
4, 813.204, 0, 0, 0.499489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499014,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0301275);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492356,-99) , 
0, 106.24, 0, 0, 0.501558,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.241034,-99) , 
0, 383.592, 1, 0, 0.50073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500256,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0860865);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477509,-99) , 
4, 171.541, 1, 0, 0.556425,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483088,-99) , 
7, 1.28446, 0, 0, 0.499538,-99) , 
7, 0.175156, 1, 0, 0.508565,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.799927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.189007,-99) , 
3, 155.006, 1, 0, 0.659245,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27287,-99) , 
0, 173.373, 0, 0, 0.380604,-99) , 
3, 134.505, 0, 0, 0.438875,-99) , 
7, 1.83915, 1, 0, 0.504495,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0559175);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.175156, 1, 1, 0.518623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.518134,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.785793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.202557,-99) , 
3, 155.006, 1, 0, 0.651588,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29028,-99) , 
0, 173.373, 0, 0, 0.384119,-99) , 
3, 134.505, 0, 0, 0.439509,-99) , 
7, 1.83915, 1, 0, 0.513601,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0555959);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.00349, 0, 1, 0.540306,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472427,-99) , 
4, 153.039, 0, 0, 0.497423,-99) , 
7, 0.175156, 1, 0, 0.504189,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.776231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.211739,-99) , 
3, 155.006, 1, 0, 0.646405,-99) , 
NN(
0, 
0, 
-1, 12.8234, 0, -1, 0.386449,-99) , 
3, 134.505, 0, 0, 0.439932,-99) , 
7, 1.83915, 1, 0, 0.500515,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0675842);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 77.3837, 1, 0, 0.589538,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470406,-99) , 
6, 2.99199, 0, 0, 0.483389,-99) , 
1, 20.8398, 1, 0, 0.519198,-99) , 
NN(
0, 
0, 
-1, 127.331, 1, -1, 0.484864,-99) , 
0, 80.2727, 1, 0, 0.495701,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0250223);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 328.079, 1, 0, 0.509972,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.244744,-99) , 
0, 383.592, 1, 0, 0.509131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.508684,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0220794);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.782665,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408443,-99) , 
2, 31.4195, 0, 0, 0.502151,-99) , 
4, 813.204, 0, 0, 0.502913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.502477,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0279382);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441225,-99) , 
3, 14.6749, 0, 0, 0.498982,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.176433,-99) , 
3, 308.532, 1, 0, 0.498253,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.238794,-99) , 
0, 383.592, 1, 0, 0.49743,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0188552);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.774486,-99) , 
NN(
0, 
0, 
-1, 281.533, 1, -1, 0.491708,-99) , 
4, 813.204, 0, 0, 0.492466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.492044,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00707679);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 328.079, 1, -1, 0.497957,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.240177,-99) , 
0, 383.592, 1, 0, 0.497154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.496732,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0321322);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491648,-99) , 
1, 10.487, 1, 0, 0.500021,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.179452,-99) , 
3, 308.532, 1, 0, 0.499309,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.238877,-99) , 
0, 383.592, 1, 0, 0.498497,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0149811);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 536.119, 0, 1, 0.505705,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.178612,-99) , 
3, 308.532, 1, 0, 0.504986,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.237658,-99) , 
0, 383.592, 1, 0, 0.504161,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.00749055);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 536.119, 0, 1, 0.50196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.178214,-99) , 
3, 308.532, 1, 0, 0.501252,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.23708,-99) , 
0, 383.592, 1, 0, 0.500441,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.00908545);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.727523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49865,-99) , 
4, 536.119, 0, 0, 0.500087,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.178014,-99) , 
3, 308.532, 1, 0, 0.499385,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.236789,-99) , 
0, 383.592, 1, 0, 0.498581,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.00818415);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 536.119, 0, 1, 0.50233,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.177769,-99) , 
3, 308.532, 1, 0, 0.501625,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.236434,-99) , 
0, 383.592, 1, 0, 0.500815,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.0085415);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.724086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498875,-99) , 
4, 536.119, 0, 0, 0.500284,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.177547,-99) , 
3, 308.532, 1, 0, 0.499585,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.236113,-99) , 
0, 383.592, 1, 0, 0.498782,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.00826565);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 536.119, 0, 1, 0.502392,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.177315,-99) , 
3, 308.532, 1, 0, 0.50169,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.235775,-99) , 
0, 383.592, 1, 0, 0.500883,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.00831178);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.720716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498944,-99) , 
4, 536.119, 0, 0, 0.500326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.177088,-99) , 
3, 308.532, 1, 0, 0.49963,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.235447,-99) , 
0, 383.592, 1, 0, 0.49883,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0286712);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4538,-99) , 
3, 14.6749, 0, 0, 0.502378,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.17686,-99) , 
3, 308.532, 1, 0, 0.501679,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.235115,-99) , 
0, 383.592, 1, 0, 0.500874,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.0150817);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.714968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495441,-99) , 
4, 536.119, 0, 0, 0.496805,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.176064,-99) , 
3, 308.532, 1, 0, 0.496123,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.233955,-99) , 
0, 383.592, 1, 0, 0.495338,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.00665463);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500529,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.175648,-99) , 
3, 308.532, 1, 0, 0.499841,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.233336,-99) , 
0, 383.592, 1, 0, 0.499048,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0107878);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497551,-99) , 
4, 536.119, 0, 0, 0.498869,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.175463,-99) , 
3, 308.532, 1, 0, 0.498186,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.233061,-99) , 
0, 383.592, 1, 0, 0.497398,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.00859535);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.501533,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.175161,-99) , 
3, 308.532, 1, 0, 0.500846,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.232613,-99) , 
0, 383.592, 1, 0, 0.500051,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.00452469);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.499388,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.17492,-99) , 
3, 308.532, 1, 0, 0.498708,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.232254,-99) , 
0, 383.592, 1, 0, 0.497921,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.0065347);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.50052,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.174793,-99) , 
3, 308.532, 1, 0, 0.499837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.232064,-99) , 
0, 383.592, 1, 0, 0.499048,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.00549316);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.49889,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.174609,-99) , 
3, 308.532, 1, 0, 0.498212,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.231789,-99) , 
0, 383.592, 1, 0, 0.497428,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.00598331);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500263,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.174454,-99) , 
3, 308.532, 1, 0, 0.499583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.231556,-99) , 
0, 383.592, 1, 0, 0.498796,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.00570495);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.49877,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.174285,-99) , 
3, 308.532, 1, 0, 0.498095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.231302,-99) , 
0, 383.592, 1, 0, 0.497312,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.00581247);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500197,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.174124,-99) , 
3, 308.532, 1, 0, 0.499519,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.231059,-99) , 
0, 383.592, 1, 0, 0.498733,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.00572652);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498747,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.173959,-99) , 
3, 308.532, 1, 0, 0.498073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.230811,-99) , 
0, 383.592, 1, 0, 0.497292,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.00573785);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500178,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.173797,-99) , 
3, 308.532, 1, 0, 0.499503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.230565,-99) , 
0, 383.592, 1, 0, 0.498718,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.00570055);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498747,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.173634,-99) , 
3, 308.532, 1, 0, 0.498075,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.230318,-99) , 
0, 383.592, 1, 0, 0.497296,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.00568784);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500172,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.173471,-99) , 
3, 308.532, 1, 0, 0.499498,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.230072,-99) , 
0, 383.592, 1, 0, 0.498715,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.00566297);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.173309,-99) , 
3, 308.532, 1, 0, 0.498083,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.229825,-99) , 
0, 383.592, 1, 0, 0.497305,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.00564439);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500169,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.173147,-99) , 
3, 308.532, 1, 0, 0.499497,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.229578,-99) , 
0, 383.592, 1, 0, 0.498715,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0106833);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.706599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497474,-99) , 
4, 536.119, 0, 0, 0.498761,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.172986,-99) , 
3, 308.532, 1, 0, 0.498093,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.229332,-99) , 
0, 383.592, 1, 0, 0.497316,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.00804268);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.501399,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.172679,-99) , 
3, 308.532, 1, 0, 0.500727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.228863,-99) , 
0, 383.592, 1, 0, 0.499944,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.00432422);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.499392,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.172449,-99) , 
3, 308.532, 1, 0, 0.498726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.228508,-99) , 
0, 383.592, 1, 0, 0.497949,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.00616004);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.172324,-99) , 
3, 308.532, 1, 0, 0.499806,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.228316,-99) , 
0, 383.592, 1, 0, 0.499026,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.0311216);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.834935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491038,-99) , 
6, 2.99912, 1, 0, 0.531353,-99) , 
NN(
0, 
0, 
-1, 296.828, 1, -1, 0.491712,-99) , 
6, 2.992, 0, 0, 0.498273,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.228042,-99) , 
0, 383.592, 1, 0, 0.497499,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.0178856);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.506417,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.176589,-99) , 
3, 308.532, 1, 0, 0.505754,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.226642,-99) , 
0, 383.592, 1, 0, 0.504961,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.00895183);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.501955,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.176059,-99) , 
3, 308.532, 1, 0, 0.501304,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.225826,-99) , 
0, 383.592, 1, 0, 0.500525,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.00447592);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.499722,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.175795,-99) , 
3, 308.532, 1, 0, 0.499076,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.225414,-99) , 
0, 383.592, 1, 0, 0.498305,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0106949);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.702806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497347,-99) , 
4, 536.119, 0, 0, 0.498605,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.175662,-99) , 
3, 308.532, 1, 0, 0.497962,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.225208,-99) , 
0, 383.592, 1, 0, 0.497195,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.00746404);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.501246,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.175344,-99) , 
3, 308.532, 1, 0, 0.5006,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.224711,-99) , 
0, 383.592, 1, 0, 0.499826,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.00415955);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.499384,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.175121,-99) , 
3, 308.532, 1, 0, 0.498742,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.224363,-99) , 
0, 383.592, 1, 0, 0.497974,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.00578998);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500424,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.174997,-99) , 
3, 308.532, 1, 0, 0.499781,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.224169,-99) , 
0, 383.592, 1, 0, 0.49901,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.00494442);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498979,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.174824,-99) , 
3, 308.532, 1, 0, 0.49834,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.223897,-99) , 
0, 383.592, 1, 0, 0.497574,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.00534135);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500216,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.174676,-99) , 
3, 308.532, 1, 0, 0.499574,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.223664,-99) , 
0, 383.592, 1, 0, 0.498805,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.00511501);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498883,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.174515,-99) , 
3, 308.532, 1, 0, 0.498245,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.223412,-99) , 
0, 383.592, 1, 0, 0.49748,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.00520154);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500162,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.174362,-99) , 
3, 308.532, 1, 0, 0.499522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.22317,-99) , 
0, 383.592, 1, 0, 0.498754,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.00513123);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498864,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.174205,-99) , 
3, 308.532, 1, 0, 0.498228,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.222923,-99) , 
0, 383.592, 1, 0, 0.497464,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.00513976);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500147,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.17405,-99) , 
3, 308.532, 1, 0, 0.499509,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.222678,-99) , 
0, 383.592, 1, 0, 0.498742,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.00510888);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498864,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.173895,-99) , 
3, 308.532, 1, 0, 0.49823,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.222432,-99) , 
0, 383.592, 1, 0, 0.497467,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.00509859);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500142,-99) , 
NN(
0, 
0, 
-1, 1.04895, 0, -1, 0.173741,-99) , 
3, 308.532, 1, 0, 0.499505,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.222188,-99) , 
0, 383.592, 1, 0, 0.498739,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.00507935);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498869,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.174474,-99) , 
3, 308.532, 1, 0, 0.498238,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.221942,-99) , 
0, 383.592, 1, 0, 0.497476,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.00506446);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.17432,-99) , 
3, 308.532, 1, 0, 0.499506,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.221698,-99) , 
0, 383.592, 1, 0, 0.498741,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.00504734);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 308.532, 1, -1, 0.498246,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.221453,-99) , 
0, 383.592, 1, 0, 0.497484,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.00503189);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500137,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.174893,-99) , 
3, 308.532, 1, 0, 0.499508,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.221208,-99) , 
0, 383.592, 1, 0, 0.498743,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.00984697);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.699064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497654,-99) , 
4, 536.119, 0, 0, 0.498882,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.174739,-99) , 
3, 308.532, 1, 0, 0.498255,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.220963,-99) , 
0, 383.592, 1, 0, 0.497494,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.00734297);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.501314,-99) , 
NN(
0, 
0, 
-1, 1.04895, 0, -1, 0.174438,-99) , 
3, 308.532, 1, 0, 0.500684,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.220483,-99) , 
0, 383.592, 1, 0, 0.499917,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.00379858);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.499482,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.175498,-99) , 
3, 308.532, 1, 0, 0.498859,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.221747,-99) , 
0, 383.592, 1, 0, 0.498102,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.00555667);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500431,-99) , 
NN(
0, 
0, 
-1, 1.04895, 0, -1, 0.175381,-99) , 
3, 308.532, 1, 0, 0.499807,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.22156,-99) , 
0, 383.592, 1, 0, 0.499048,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.004657);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.499045,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.176186,-99) , 
3, 308.532, 1, 0, 0.498426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500526,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.22252,-99) , 
0, 383.592, 1, 0, 0.497674,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.00509034);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500209,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.176042,-99) , 
3, 308.532, 1, 0, 0.499588,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.22229,-99) , 
0, 383.592, 1, 0, 0.498834,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.00485492);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 308.532, 1, -1, 0.498321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.223171,-99) , 
0, 383.592, 1, 0, 0.497574,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.00495659);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.176589,-99) , 
3, 308.532, 1, 0, 0.499535,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.22293,-99) , 
0, 383.592, 1, 0, 0.498785,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.0296692);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.82636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49134,-99) , 
6, 2.99912, 1, 0, 0.529925,-99) , 
NN(
0, 
0, 
-1, 296.828, 1, -1, 0.492043,-99) , 
6, 2.992, 0, 0, 0.498301,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.223789,-99) , 
0, 383.592, 1, 0, 0.497558,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.0166499);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.506052,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.180747,-99) , 
3, 308.532, 1, 0, 0.505438,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.222295,-99) , 
0, 383.592, 1, 0, 0.504677,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.00833183);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.501898,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.180216,-99) , 
3, 308.532, 1, 0, 0.501294,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.225187,-99) , 
0, 383.592, 1, 0, 0.500555,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.0077795);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.696459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498617,-99) , 
4, 536.119, 0, 0, 0.499819,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.179951,-99) , 
3, 308.532, 1, 0, 0.49922,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.226644,-99) , 
0, 383.592, 1, 0, 0.498492,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.00797607);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.50174,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.179702,-99) , 
3, 308.532, 1, 0, 0.501139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.228011,-99) , 
0, 383.592, 1, 0, 0.500411,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.00399352);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.49975,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.179446,-99) , 
3, 308.532, 1, 0, 0.499153,-99) , 
NN(
0, 
0, 
-1, 272.79, 0, -1, 0.227597,-99) , 
0, 383.592, 1, 0, 0.498431,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.00511985);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498754,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.179318,-99) , 
3, 308.532, 1, 0, 0.498159,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.2283,-99) , 
0, 383.592, 1, 0, 0.497442,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.00453789);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500033,-99) , 
NN(
0, 
0, 
-1, 404.608, 1, -1, 0.179153,-99) , 
3, 308.532, 1, 0, 0.499437,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.228034,-99) , 
0, 383.592, 1, 0, 0.498718,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.00481493);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498901,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.179822,-99) , 
3, 308.532, 1, 0, 0.498309,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.228834,-99) , 
0, 383.592, 1, 0, 0.497595,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.00465943);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500105,-99) , 
NN(
0, 
0, 
-1, 1.04895, 0, -1, 0.179666,-99) , 
3, 308.532, 1, 0, 0.499511,-99) , 
NN(
0, 
0, 
-1, 272.79, 0, -1, 0.228582,-99) , 
0, 383.592, 1, 0, 0.498794,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.00472301);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498942,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.180354,-99) , 
3, 308.532, 1, 0, 0.498353,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.229405,-99) , 
0, 383.592, 1, 0, 0.497642,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.00467587);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500123,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.180201,-99) , 
3, 308.532, 1, 0, 0.499532,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.229157,-99) , 
0, 383.592, 1, 0, 0.498819,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.00932889);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497776,-99) , 
4, 536.119, 0, 0, 0.498956,-99) , 
NN(
0, 
0, 
-1, 1.04895, 0, -1, 0.180049,-99) , 
3, 308.532, 1, 0, 0.498368,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.229984,-99) , 
0, 383.592, 1, 0, 0.497661,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.00691607);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.50126,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.18143,-99) , 
3, 308.532, 1, 0, 0.500672,-99) , 
NN(
0, 
0, 
-1, 272.79, 0, -1, 0.229491,-99) , 
0, 383.592, 1, 0, 0.499959,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.00351613);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.499534,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.181204,-99) , 
3, 308.532, 1, 0, 0.49895,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.230716,-99) , 
0, 383.592, 1, 0, 0.498246,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.00520572);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500413,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.181089,-99) , 
3, 308.532, 1, 0, 0.499828,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.23053,-99) , 
0, 383.592, 1, 0, 0.499122,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.00434076);
  fForest.push_back( 
NN(
0, 
0, 
-1, 383.592, 1, -1, 0.49783,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.00475972);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.181562,-99) , 
3, 308.532, 1, 0, 0.499617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.231023,-99) , 
0, 383.592, 1, 0, 0.498915,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.00453382);
  fForest.push_back( 
NN(
0, 
0, 
-1, 383.592, 1, -1, 0.497733,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.0046339);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500145,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.18208,-99) , 
3, 308.532, 1, 0, 0.499566,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.231575,-99) , 
0, 383.592, 1, 0, 0.498867,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.00456879);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498989,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.181926,-99) , 
3, 308.532, 1, 0, 0.498412,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.231326,-99) , 
0, 383.592, 1, 0, 0.497716,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.00458625);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500131,-99) , 
NN(
0, 
0, 
-1, 404.608, 1, -1, 0.181775,-99) , 
3, 308.532, 1, 0, 0.499552,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.23214,-99) , 
0, 383.592, 1, 0, 0.498857,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.0045627);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 278.819, 1, -1, 0.498986,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 404.608, 1, 0, 0.182458,-99) , 
3, 308.532, 1, 0, 0.498412,-99) , 
NN(
0, 
0, 
-1, 272.79, 0, -1, 0.231893,-99) , 
0, 383.592, 1, 0, 0.49772,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.00456074);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 278.819, 1, 0, 0.500127,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.04895, 0, 0, 0.182306,-99) , 
3, 308.532, 1, 0, 0.499551,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.232706,-99) , 
0, 383.592, 1, 0, 0.498859,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.00454748);
  fForest.push_back( 
NN(
0, 
0, 
-1, 383.592, 1, -1, 0.497726,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.00353036);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 328.079, 1, 0, 0.499914,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.234679,-99) , 
0, 383.592, 1, 0, 0.49923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498863,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.00405894);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 328.079, 1, -1, 0.499032,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.23449,-99) , 
0, 383.592, 1, 0, 0.498352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.497986,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.0258073);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.818674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492983,-99) , 
6, 2.99912, 1, 0, 0.529938,-99) , 
NN(
0, 
0, 
-1, 296.828, 1, -1, 0.493711,-99) , 
6, 2.992, 0, 0, 0.499687,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.23287,-99) , 
0, 383.592, 1, 0, 0.498998,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.0161322);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 328.079, 1, 0, 0.506259,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.238933,-99) , 
0, 383.592, 1, 0, 0.505576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.50521,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.0080714);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 328.079, 1, 0, 0.502232,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.238051,-99) , 
0, 383.592, 1, 0, 0.501561,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.5012,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.00405273);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.81777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499613,-99) , 
4, 813.204, 0, 0, 0.500217,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.237608,-99) , 
0, 383.592, 1, 0, 0.499551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499194,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.00603848);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 328.079, 1, 0, 0.501227,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.237385,-99) , 
0, 383.592, 1, 0, 0.500558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500201,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.00501207);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.816343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499119,-99) , 
4, 813.204, 0, 0, 0.49972,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.237052,-99) , 
0, 383.592, 1, 0, 0.499055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.4987,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.00592123);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.802095,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.141669,-99) , 
3, 284.712, 1, 0, 0.500038,-99) , 
4, 813.204, 0, 0, 0.500619,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.23538,-99) , 
0, 383.592, 1, 0, 0.499945,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.00306508);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 328.079, 1, -1, 0.499493,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.237847,-99) , 
0, 383.592, 1, 0, 0.498833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498479,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.00407466);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 328.079, 1, 0, 0.50026,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.237677,-99) , 
0, 383.592, 1, 0, 0.499598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499244,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.00355523);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 328.079, 1, -1, 0.499242,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.237451,-99) , 
0, 383.592, 1, 0, 0.498583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498231,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.00380219);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 328.079, 1, 0, 0.500131,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.237253,-99) , 
0, 383.592, 1, 0, 0.49947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.499117,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.00603231);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.814614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498586,-99) , 
4, 813.204, 0, 0, 0.499182,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 672.374, 0, 0, 0.237041,-99) , 
0, 383.592, 1, 0, 0.498523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498172,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.00488105);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 328.079, 1, 0, 0.500684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.500339,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.235318,-99) , 
0, 383.592, 1, 0, 0.499671,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.00308882);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 328.079, 1, -1, 0.499466,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.237587,-99) , 
0, 383.592, 1, 0, 0.49881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.49846,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.00441222);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.80012,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.143642,-99) , 
3, 284.712, 1, 0, 0.49932,-99) , 
4, 813.204, 0, 0, 0.499895,-99) , 
NN(
0, 
0, 
-1, 672.374, 0, -1, 0.236026,-99) , 
0, 383.592, 1, 0, 0.499231,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.0037345);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 328.079, 1, -1, 0.499139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 272.79, 0, 0, 0.238214,-99) , 
0, 383.592, 1, 0, 0.498487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 159.164, 1, 0, 0.498138,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_ee_eq1j::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_ee_eq1j::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
